redpanda-data/console

- README.md
- backend/go.mod
- backend/pkg/api/api.go
- backend/pkg/api/config.go
- backend/pkg/kafka/list_messages.go
- backend/pkg/owl/cluster_info.go
- backend/pkg/owl/config.go
- backend/pkg/owl/consumer_group_lag.go
- backend/pkg/owl/consumer_group_overview.go
- backend/pkg/owl/log_dir.go
- backend/pkg/owl/service.go
- backend/pkg/owl/topic_config.go
- backend/pkg/owl/topic_overview.go
- backend/pkg/owl/topic_partitions.go
adds blacklist cmd line parameter
prevents display and backend calls for blacklisted topics
> topics blacklist

- frontend/src/components/pages/topics/Tab.Messages.tsx
- frontend/src/state/backendApi.ts
- frontend/src/utils/tsxUtils.tsx
As per title, please let me know if anything lacking.
Cheers,
RJ
> More info on the StatusIndicator and add Cancel Search on Messages Tab

- frontend/src/utils/tsxUtils.tsx
Some small fix on alignment issue on status bar
> Minor fix on alignment

- frontend/src/components/pages/topics/Tab.Messages.tsx
- frontend/src/utils/tsxUtils.tsx
- Remove the modal shown on Filter Enabled toggle when no filter exists
- Adding some icons on the progress modal
- Remove unused dependencies on `frontend/src/components/pages/topics/Tab.Messages.tsx `
Cheers,
RJ
> Minor fix on enabledFilter and removed unused deps

- frontend/src/components/pages/admin/Admin.RoleBindings.tsx
- frontend/src/components/pages/admin/Admin.Roles.tsx
- frontend/src/components/pages/admin/Admin.Users.tsx
- frontend/src/utils/arrayExtensions.ts
The bugs and issue mentioned on #53 should be fixed.
Some works need to be done on Backend to implement the features better. Like the mappings between users and its rolebindings, etc. What do you guys think.
Cheers,
RJ
> [WIP] #53: Fixing bugs and some issue

- backend/pkg/api/handle_topic_messages.go
- backend/pkg/api/websocket_progress_reporter.go
- backend/pkg/kafka/partition_consumer.go
- backend/pkg/owl/list_messages.go
- backend/pkg/owl/list_messages_test.go
> Search all partitions if filter

- frontend/src/components/pages/topics/Tab.Messages.tsx
- frontend/src/index.css
- frontend/src/utils/filterHelper.ts
Hey, it's still in progress for #70, but review is welcome. 
Cheers,
RJ
> [In progress] #70 Improving the UX of Filter

- frontend/src/components/pages/topics/Tab.Messages.tsx
- frontend/src/index.css
- frontend/src/state/ui.ts
- frontend/src/utils/tsxUtils.tsx
So I added the more options on copy. I think from the UX capability it's probably fine to do it in two clicks. As it is also not clear what they want to copy just from one click in my opinion. I changed the icon to triple dots, as for the usability perspective it should mean there should be more options after clicking. But if you guys are not up for it, just changed for another icon.
Anyway if anything to change lemme know.
Cheers,
RJ
> #30 Adding more copy options on the row

- backend/pkg/api/handle_cluster.go
- backend/pkg/api/routes.go
- backend/pkg/kafka/describe_broker_config.go
- backend/pkg/kafka/service.go
- backend/pkg/owl/broker_config.go
- frontend/src/components/pages/brokers/Broker.List.tsx
- frontend/src/components/pages/topics/QuickInfo.tsx
- frontend/src/components/pages/topics/Tab.Config.tsx
- frontend/src/components/pages/topics/Tab.Partitions.tsx
- frontend/src/index.scss
- frontend/src/state/backendApi.ts
- frontend/src/state/restInterfaces.ts
- frontend/src/state/ui.ts
- frontend/src/utils/tsxUtils.tsx
This PR closes #84 . Frontend is still to be done.
> Add endpoint to fetch all brokers' config entries

- frontend/src/components/pages/topics/Tab.Messages.tsx
- frontend/src/utils/filterHelper.ts
Hello everyone,
As per title. I encoded the special character on the message filter with hex encoding, before it was pushed to the backend.
Lemme know if anything needed to be changed.
Cheers,
RJ
> Encode the filter code with hex encoding before sending to backend

- backend/pkg/schema/client.go
- backend/pkg/schema/config_tls.go
- docs/config/kowl-business.yaml
- docs/config/kowl.yaml
Our SchemaRegistry need TLS authentication. This PR make the ability to send TLS certificate when connecting to it.
> Add schemaregistry TLS authentication

- backend/pkg/kafka/config_helper.go
- backend/pkg/kafka/config_sasl.go
- backend/pkg/kafka/config_sasl_gssapi.go
- docs/config/kowl-business.yaml
- docs/config/kowl.yaml
Got the same issue with kowl as this issue in [kminion #111](https://github.com/cloudhut/kminion/issues/111) so I basically just copied the implementation that @weeco did there.
I have built the docker file and tested it locally and it fixed the problem.
> Added option to disable Kerberos FAST

- backend/pkg/kafka/client_hooks.go
The hook functions were named incorrectly, which resulted in empty/non-functional metrics.
Use the correct funcs and fix the metrics.
> Fix kafka metrics

- docs/local/config.yaml
- docs/local/docker-compose.yaml
Updated to kowl 1.5.0 and Confluent Platform 7.0.1.
Added Connect and Schema Registry
> Updated to kowl 1.5.0 and Confluent Platform 7.0.1 

- README.md
Hi, we are currently using Kowl on the following environments at [opt-nc](https://github.com/opt-nc) : 
- Developer workstation
- Integration
- Testing
- Production
Thanks for delivering this product as an open source software.
> Add OPT-NC at companies using Kowl

- .github/workflows/build-image.yml
needed in order to be able to push to docker hub
> Add dockerhub login step

- frontend/src/components/pages/connect/helper.tsx
- frontend/src/components/pages/schemas/Schema.List.tsx
- frontend/src/components/pages/topics/Tab.Docu.tsx
Fix incorrect links pointing to old kowl.yaml instead of console.yaml under docs
> frontend: fix incorrect links

- helm/console/templates/deployment.yaml
extra container configuration was missing in deployment.yaml
> Updated deployment.yaml with extracontainer configuration

- backend/pkg/proto/service.go
This commit adds better support for protobuf deserialization by allowing the console to deserialize custom proto messages that are supplied to fields with the `google.protobuf.Any` type.
Before this change, if your protobuf message contained a field of type `google.protobuf.Any` and the value supplied at runtime was not a standard proto message (e.g. `google.protobuf.Timestamp`), then `msg.MarshalJSON` (called from `deserializeProtobufMessageToJSON`) would yield the following error:
```
failed to marshal protobuf message to JSON:
unknown message type \"<type-url>\"
```
This error was emitted by the `github.com/jhump/protoreflect` because it would fail to resolve the 'type url' of the value supplied to the `google.protobuf.Any` field. This error would occur even if the type was available …
> proto: support protobuf any

- frontend/src/components/routes.tsx
- frontend/src/index.scss
Replace Link component and use onClick handler to navigate: 
programatically on the main menu, enabling collapsed menu to work as
expected
#445 
https://www.loom.com/share/e8bf6ac8cd3e4d17b2d7e969cf98741f
> fix(frontend): fix navigation on collapesed menu.

- frontend/src/config.ts
extend config to support clusterId for embedded console
> feat(fronted): add clusterId to setConfig on embedded console

- frontend/src/components/misc/ErrorDisplay.tsx
- frontend/src/components/misc/PageContent.tsx
- frontend/src/components/misc/Section.tsx
- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/admin/AdminPage.tsx
- frontend/src/components/pages/brokers/Broker.List.tsx
- frontend/src/components/pages/connect/Cluster.Details.tsx
- frontend/src/components/pages/connect/Connector.Details.tsx
- frontend/src/components/pages/connect/CreateConnector.tsx
- frontend/src/components/pages/connect/Overview.tsx
- frontend/src/components/pages/connect/helper.tsx
- frontend/src/components/pages/consumers/Group.Details.tsx
- frontend/src/components/pages/consumers/Group.List.tsx
- frontend/src/components/pages/quotas/Quotas.List.tsx
- frontend/src/components/pages/reassign-partitions/ReassignPartitions.tsx
- frontend/src/components/pages/schemas/Schema.Details.tsx
- frontend/src/components/pages/schemas/Schema.List.tsx
- frontend/src/components/pages/topics/Topic.Details.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
- frontend/src/index-cloud-integration.scss
- frontend/src/index.scss
* Refactors Card to Section component for dark mode.
* Adds PageContent to abstract motion.div for each page.
Note: does not fix tables etc, that PR is coming separately.
> refactor: card to section

- frontend/package-lock.json
- frontend/package.json
- frontend/scripts/fetch-monaco.mjs
- update monaco editor to new versio 0.34.0
- extend fetch monaco editor script to fetch version from the package.json
> chore(frontent): update monaco-editor to version 0.34.0

- .github/workflows/kics-iac.yml
add kics IAC security scanning to the console project
> add kics scanning 

- frontend/src/index.scss
> temp fix user button until sidebar supports placement

- backend/pkg/connect/guides/mm2_checkpoint_connector.json
- backend/pkg/connect/guides/mm2_source_connector.json
UI wizard for the MirrorCheckpointConnector
> Mm2 consumer groups

- CHANGELOG.md
> Add changelog for v2.0.0 and v2.1.0

- backend/pkg/api/handle_schema.go
- backend/pkg/schema/client.go
- frontend/src/components/pages/schemas/Schema.Details.tsx
- frontend/src/components/pages/schemas/Schema.List.tsx
- frontend/src/state/backendApi.ts
> Url escape schema subjects

- frontend/src/EmbeddedApp.tsx
make sure current fonts are required on the embedded console, so we have every font available
> fix(frontend): require fonts on embedded console

- backend/pkg/config/redpanda_admin_api.go
> backend: Validate redpanda admin api config urls

- backend/pkg/kafka/consumer_worker.go
> backend: Recover from panics in message worker

- .github/workflows/backend-snyk-scan.yml
this workflow will scan the `master` and `release-*` branches and send results to snyk.
> adds snyk scanning workflow

- frontend/src/components/pages/consumers/Group.Details.tsx
- frontend/src/components/pages/topics/CreateTopicModal/CreateTopicModal.tsx
- frontend/src/components/pages/topics/QuickInfo.tsx
- frontend/src/components/pages/topics/Tab.Config.tsx
remove dynamic config entries, just show retention/segment ms/bytes based on cleanup.policy
> rework topic details statistics bar

- README.md
this is a follow-up to issue https://github.com/redpanda-data/devprod/issues/378
> readme: update location of docker image

- frontend/src/components/pages/connect/CreateConnector.tsx
- frontend/src/state/connect/state.ts
let the creation of connectors passing any key
Resolves: #647
> fix(frontend): create connectors fix

- frontend/src/components/misc/login.tsx
- frontend/src/utils/svg/AzureADLogo.tsx
This PR adds the Azure AD logo when configuring SSO with Azure.
> frontend: Add Azure AD logo for enterprise SSO

- backend/pkg/proto/service.go
Fixing:  #606
Combine FileSystem and GitHub proto schema files to make both registries work together
> backend: support multiple source(github-filesystem) for proto schema registry

- backend/pkg/console/brokers.go
- backend/pkg/kafka/consumer.go
This PR addresses two distinct issues/improvements:
1. A message search would often times log an error message for context cancelled. This confused users as it would indicate something is wrong. This is a totally expected message because as soon the message search is considered complete we cancel the context and no longer wait for messages from other partitions which may already be "drained".
2. On the /brokers overview page we try to describe every broker's log dir. If a single broker fails to respond to this request the overall API request currently fails. This PR addresses this issue by continuing with the request and returning a partial response.
> Improve error handling

- backend/pkg/console/consumer_group_offsets.go
- backend/pkg/kafka/list_consumer_group_offsets.go
Franz-go nowadays can request group offsets in bulk (if supported by target kafka cluster). If it's not supported the client will split the request so that we no longer need to worry about it.
> backend: Rely on franz-go to fetch grp offsets in bulk

- backend/pkg/connector/guide/debezium_postgres_source.go
- backend/pkg/connector/patch/debezium_mysql_source.go
- backend/pkg/connector/patch/debezium_postgres_source.go
* added database.sslmode property to debezium postgres connector
* use radio-group component for ssl mode in postgres and mysql connectors
> connectors: added database.sslmode property to debezium postgres connector

- backend/pkg/kafka/consumer.go
- backend/pkg/kafka/consumer_worker.go
- backend/pkg/kafka/deserializer.go
- frontend/src/components/pages/topics/Tab.Messages/index.tsx
- frontend/src/state/backendApi.ts
- frontend/src/state/restInterfaces.ts
> msgviewer: Support for utf8 control char payloads

- .github/workflows/kics-iac.yml
exclude docs dir from KICS scanning
> exclude docs dir from KICS

- backend/pkg/connector/interceptor/debezium_mysql_source_hook.go
- backend/pkg/connector/interceptor/mirror_hook.go
- backend/pkg/connector/patch/common.go
- backend/pkg/connector/patch/jdbc_sink.go
- backend/pkg/connector/patch/mongo.go
- backend/pkg/connector/patch/redpanda_gcs_sink.go
* improved documentations in jdbc connector
* replaced Kafka with Redpanda  docs and property names
> connectors: improved documentations in jdbc connector, replaced Kafka with Redpanda

- frontend/src/state/backendApi.ts
there where some null/undefined mapping, when the request is unauthorized
Related to: redpanda-data/cloudv2#6318
> fix(frontend): for over null/undefined

- backend/pkg/connector/guide/mirror_source.go
- backend/pkg/connector/interceptor/mirror_hook.go
> connectors: added support for 'auto.offset.reset' MM2 property

- backend/pkg/connector/interceptor/mirror_hook.go
Issue: https://github.com/redpanda-data/cloudv2/issues/6816
> connectors: changed auto.offset.reset value to 'none'

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
- frontend/src/components/pages/topics/Topic.Details.tsx
- frontend/src/components/routes.tsx
- frontend/src/config.ts
- frontend/src/utils/env.ts
Change how isServerless() is implemented; going from APP_FEATURES html/env to injected config props by cloud-ui
> Serverless UI

- backend/pkg/config/kafka.go
- backend/pkg/config/kafka_sasl_oauth.go
- backend/pkg/kafka/config_helper.go
- docs/config/console.yaml
See https://github.com/redpanda-data/console/issues/699
> Added clientid, clientsecret and tokenendpoint to SASLMechanismOAuthBearer mechanism

- .github/workflows/backend-lint-test.yml
Somehow this commit did not make it into my PR #755.
> backend: add integration tag to verify github workflow

- backend/pkg/schema/client.go
- backend/pkg/schema/service.go
> backend: fix avro deserialization

- frontend/src/components/misc/BrokerList.tsx
- frontend/src/components/misc/ConfigList.tsx
- frontend/src/components/misc/HideStatisticsBarButton.tsx
- frontend/src/components/misc/KowlJsonView.module.scss
- frontend/src/components/misc/KowlJsonView.tsx
- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/acls/CreateServiceAccountEditor.tsx
- frontend/src/components/pages/acls/PrincipalGroupEditor.tsx
- frontend/src/components/pages/admin/Admin.Users.tsx
- frontend/src/components/pages/connect/Connector.Details.tsx
- frontend/src/components/pages/connect/Overview.tsx
- frontend/src/components/pages/connect/dynamic-ui/List.tsx
- frontend/src/components/pages/connect/dynamic-ui/forms/SecretInput.tsx
- frontend/src/components/pages/consumers/Group.Details.tsx
- frontend/src/components/pages/consumers/Modals.tsx
- frontend/src/components/pages/overview/Overview.tsx
- frontend/src/components/pages/schemas/Schema.Details.tsx
- frontend/src/components/pages/topics/PublishMessagesModal/PublishMessagesModal.tsx
- frontend/src/components/pages/topics/Tab.Config.tsx
- frontend/src/components/pages/topics/Tab.Messages/index.tsx
- frontend/src/components/pages/topics/Topic.Details.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
- frontend/src/components/pages/topics/TopicConfiguration.tsx
- frontend/src/index.scss
- frontend/src/utils/tsxUtils.tsx
Moved all Tooltip component instances to use the Redpanda Tooltip variant.
> ui: Migration - Tooltip Component

- backend/pkg/filesystem/util_unix_test.go
- backend/pkg/filesystem/util_windows_test.go
Fixes a couple linting issues that slipped in via https://github.com/redpanda-data/console/pull/812
> backend: fix linting issues

- frontend/src/components/pages/connect/helper.tsx
> connectors: added IBM MQ and JMS connectors to connectors helper

- frontend/src/components/pages/reassign-partitions/components/ActiveReassignments.tsx
- frontend/src/components/pages/topics/Tab.Messages/index.tsx
- frontend/src/utils/tsxUtils.tsx
Migrated progress bar to Chakra
> misc: Chakra progress bar

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/misc/buttons/data-refresh/Component.tsx
Since some of the elements are still using Antd, in some places we're forced to still use a Portal.
> Fixes popover issue with text overlay

- frontend/src/components/pages/acls/PrincipalGroupEditor.tsx
- frontend/src/components/pages/topics/Tab.Messages/PreviewSettings.tsx
We need to merge #847 first, and change base of this PR afterwards.
> Autocomplete migration

- frontend/src/components/misc/UserButton.tsx
- frontend/src/components/misc/UserPreferences.tsx
- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/topics/Tab.Messages/index.tsx
- frontend/src/components/routes.tsx
With this migration, I had to do some visual compromises, because somewhere we had a lack of Chakra's UI support:
Turned into:
> Migrated Dropdown and Menu components

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/misc/ErrorDisplay.tsx
- frontend/src/components/pages/topics/Tab.Config.tsx
- frontend/src/components/pages/topics/Topic.Details.tsx
- frontend/src/utils/createAutoModal.tsx
> Basic migration of Result to Chakra

- frontend/src/utils/tsxUtils.tsx
Fixes a behaviour where a toast is unexpectedly closed during a long search.
> Fixes closing of a tooltip

- backend/pkg/proto/service.go
- backend/pkg/schema/embed/embed.go
- backend/pkg/schema/embed/protobuf/confluent/meta.proto
- backend/pkg/schema/embed/protobuf/confluent/types/decimal.proto
- backend/pkg/schema/embed/protobuf/google/type/README.md
- backend/pkg/schema/embed/protobuf/google/type/calendar_period.proto
- backend/pkg/schema/embed/protobuf/google/type/color.proto
- backend/pkg/schema/embed/protobuf/google/type/date.proto
- backend/pkg/schema/embed/protobuf/google/type/datetime.proto
- backend/pkg/schema/embed/protobuf/google/type/dayofweek.proto
- backend/pkg/schema/embed/protobuf/google/type/decimal.proto
- backend/pkg/schema/embed/protobuf/google/type/expr.proto
- backend/pkg/schema/embed/protobuf/google/type/fraction.proto
- backend/pkg/schema/embed/protobuf/google/type/interval.proto
- backend/pkg/schema/embed/protobuf/google/type/latlng.proto
- backend/pkg/schema/embed/protobuf/google/type/localized_text.proto
- backend/pkg/schema/embed/protobuf/google/type/money.proto
- backend/pkg/schema/embed/protobuf/google/type/month.proto
- backend/pkg/schema/embed/protobuf/google/type/phone_number.proto
- backend/pkg/schema/embed/protobuf/google/type/postal_address.proto
- backend/pkg/schema/embed/protobuf/google/type/quaternion.proto
- backend/pkg/schema/embed/protobuf/google/type/timeofday.proto
- backend/pkg/schema/service.go
> Release 2.3: Add common proto types

- frontend/src/components/layout/Header.tsx
- frontend/src/components/pages/consumers/Group.Details.tsx
- frontend/src/index.scss
This should be a 1:1 replacement. I've checked usages everywhere and tested.
We can always adjust this later with more functionality.
> Migration of a breadcrumb

- .github/workflows/kics-iac.yml
> kics exclude openapi defs

- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/connect/Cluster.Details.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
- frontend/src/components/pages/topics/TopicConfiguration.tsx
Edits to copy/text across various pages to introduce consistency. Addresses all the client-side Console UI-related changes specified in #9774.
Issue: #9774
> fix: text/copy edits for consistency

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
- frontend/src/components/pages/topics/Topic.Details.tsx
Migrates the remaining usages of AntD Typography
> Migrates Typography to Chakra

- frontend/src/components/misc/KowlTable.tsx
- frontend/src/components/misc/UserPreferences.tsx
- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/topics/CreateTopicModal/CreateTopicModal.tsx
- frontend/src/components/pages/topics/DeleteRecordsModal/DeleteRecordsModal.module.scss
- frontend/src/components/pages/topics/DeleteRecordsModal/DeleteRecordsModal.tsx
- frontend/src/components/pages/topics/Tab.Messages/PreviewSettings.tsx
- frontend/src/components/pages/topics/TopicConfiguration.tsx
- frontend/src/index.scss
> Migrate Input Components to Chakra

- backend/pkg/api/handle_topic_messages.go
- backend/pkg/api/routes.go
> backend: add log message if cors check fails

- frontend/src/components/pages/topics/Topic.Produce.tsx
- frontend/src/utils/utils.ts
> Sets base64 validation for producing message

- frontend/src/components/pages/topics/Topic.List.tsx
> Change to render the number of partitions and replicas

- .github/workflows/backend-lint-test.yml
- backend/go.mod
- backend/go.sum
Use larger machine types and update to Go 1.21
> Update GitHub workflows

- frontend/src/components/pages/topics/CreateTopicModal/CreateTopicModal.tsx
- frontend/src/components/pages/topics/DeleteRecordsModal/DeleteRecordsModal.module.scss
- frontend/src/components/pages/topics/DeleteRecordsModal/DeleteRecordsModal.tsx
- frontend/src/components/pages/topics/TopicConfiguration.scss
Dependent on https://github.com/redpanda-data/ui/pull/442
> Migrates slider component to Chakra

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
> frontend: rework troubleshoot report to use table

- backend/pkg/api/connect/interceptor/endpoint_check.go
The endpoint checker currently checks whether
the request on the given procedure matches
the configuration. If there's a misconfiguration
this can severely impact the Console UX, which
should never be desired. Thus, we are adding
an alwaysEnabledProcedures option here. This
ensures that endpoints that are used by the
frontend will always pass the endpoint check
interceptor.
> backend: add always enabled procedures

- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/admin/AdminPage.tsx
- frontend/src/components/pages/connect/Cluster.Details.tsx
- frontend/src/components/pages/connect/Connector.Details.tsx
- frontend/src/components/pages/connect/CreateConnector.tsx
- frontend/src/components/pages/connect/Overview.tsx
- frontend/src/components/pages/consumers/Group.Details.tsx
- frontend/src/components/pages/consumers/Group.List.tsx
- frontend/src/components/pages/overview/Broker.Details.tsx
- frontend/src/components/pages/overview/Overview.tsx
- frontend/src/components/pages/quotas/Quotas.List.tsx
- frontend/src/components/pages/topics/Topic.Details.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
Fixes #857 
Fixes #641
I'm not sure why `force` flag was set to `false`, I tried to figure it out, but didn't come up with any theory.
This should however not do any harm AFAIK, there were already some places where it was set to `true` already.
> reloads data when user re-enters pages

- frontend/src/components/pages/topics/Tab.Messages/PreviewSettings.tsx
Let's wait for a confirmation in https://github.com/redpanda-data/console/issues/915 first.
> Pattern help in a drawer

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
- frontend/src/state/backendApi.ts
- frontend/src/state/ui.ts
> frontend: allow selecting (overriding) key/value deserializer for topics

- frontend/src/components/misc/SearchBar.tsx
- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/admin/Admin.Users.tsx
- frontend/src/components/pages/consumers/Group.List.tsx
- frontend/src/components/pages/schemas/Schema.List.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
> Regexp search for tables in console

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
> Fixes an exception when choosing non-existing column in Table definition

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
- frontend/src/components/pages/topics/Tab.Messages/styles.module.scss
- frontend/src/utils/animationProps.tsx
I've bottom aligned it (because of labels) for now.
> Fixes alignment of items in a toolbar

- docs/config/console.yaml
> Document new maxDeserializationPayloadSize config

- frontend/src/components/pages/topics/Topic.List.tsx
Fixes sorting on `totalSizeBytes`
> Fixes topic sorting on size

- frontend/src/components/pages/connect/CreateConnector.tsx
> Fixes Back button in Connector wizard fixes #719

- backend/pkg/connector/interceptor/snowflake_hook.go
- backend/pkg/connector/interceptor/snowflake_hook_test.go
removed converter limitation on SNOWPIPE_STREAMING setting for Snowflake connector
> connectors: removed converter limitation on SNOWPIPE_STREAMING

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/pages/connect/Cluster.Details.tsx
- frontend/src/components/pages/connect/Connector.Details.tsx
- frontend/src/components/pages/consumers/Modals.tsx
- frontend/src/components/pages/overview/Broker.Details.tsx
- frontend/src/components/pages/overview/Overview.tsx
- frontend/src/components/pages/reassign-partitions/components/ActiveReassignments.tsx
- frontend/src/components/pages/topics/Tab.Partitions.tsx
Dependent on https://github.com/redpanda-data/ui/pull/464
> Hide pagination is data length is less than a default page

- frontend/src/components/misc/SearchBar.tsx
- frontend/src/components/pages/connect/Cluster.Details.tsx
- frontend/src/state/ui.ts
This provides a temporary way how to filter connectors. The proper fix taking advantage of `SearchBar` filtering is on it's way.
> Provides tmp connector filtering

- backend/pkg/api/connect/service/console/service.go
- backend/pkg/api/handle_topic_messages_integration_test.go
> backend: add filter code checks to list message RPC

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
> Update msg too large warning

- backend/pkg/api/connect/errors/errors.go
- backend/pkg/api/connect/errors/google_rpc.go
- backend/pkg/api/connect/errors/kafka.go
- Moved a func into the kafka pkg
- Fixed the status converter func to report the right status code
> Minor refactoring

- backend/.golangci.yaml
- backend/pkg/api/connect/service/console/service.go
- backend/pkg/api/connect/service/console/stream_progress_reporter.go
- backend/pkg/api/handle_schema_registry_test.go
- backend/pkg/config/kafka_sasl_oauth.go
Added a few ne linters and fixed the new findings
> Update lint config

- .github/workflows/bsr-push.yml
- taskfiles/proto.yaml
Adds a manual dispatch GitHub Action to push the protos to Bug Schema Registry.
> ci: add buf push github action

- backend/pkg/api/connect/errors/redpanda.go
- backend/pkg/api/connect/errors/redpanda_test.go
- backend/pkg/api/connect/service/transform/handle_transforms.go
- backend/pkg/api/connect/service/transform/service.go
- backend/pkg/api/connect/service/user/service.go
- taskfiles/backend.yaml
Properly parse admin api errors and bubble up the error message returned by Redpanda to the response.
> Parse redpanda errors

- frontend/src/components/misc/ConfigList.tsx
- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/connect/Cluster.Details.tsx
- frontend/src/components/pages/connect/Overview.tsx
- frontend/src/components/pages/consumers/Group.List.tsx
- frontend/src/components/pages/reassign-partitions/Step1.Partitions.tsx
- frontend/src/components/pages/schemas/Schema.List.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
> Show whole content in the tables

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/pages/topics/Tab.Messages/index.tsx
https://www.loom.com/share/bdc1a062d4574134b13520faaee5d987
> Fixes an exception related to the failure inside chakra select hook

- frontend/src/components/pages/topics/CreateTopicModal/CreateTopicModal.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
- frontend/src/components/pages/topics/Topic.Produce.tsx
Refer to: https://github.com/redpanda-data/console-enterprise/issues/281
> Serverless fixes

- frontend/src/components/misc/SearchBar.tsx
- frontend/src/components/pages/connect/Cluster.Details.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
https://www.loom.com/share/fe30b1ba72c74c63985e1222318b3798?from_recorder=1&focus_title=1
> Search statistics are shown next to the searchbar

- frontend/src/components/pages/topics/Topic.List.tsx
- frontend/tests/topic.spec.ts
I've fixed this regression that was introduced yesterday + added e2e tests so that this is being always checked.
> Show internal topics fixed

- frontend/src/components/pages/schemas/EditCompatibility.tsx
- frontend/src/components/pages/schemas/Schema.Create.tsx
Fixes https://github.com/redpanda-data/console-enterprise/issues/190
I've checked and only found these 2 occurrences where we missed proper breadcrumbs. In case there are more, feel free to comment. I need to check this in a CloudUI before merging, but I don't have access now.
> Adds breadcrumbs for more pages

- frontend/src/components/pages/acls/PrincipalGroupEditor.tsx
I've also migrated some styles to Charka and made them more consistent with the theme. Can you please check whether it's OK @ivpanda?
> Fixes ACL Modal overflow

- frontend/src/components/pages/topics/CreateTopicModal/CreateTopicModal.tsx
- frontend/src/components/pages/topics/Tab.Messages/index.tsx
> Adds support for compact/delete policy

- backend/go.mod
- backend/go.sum
- backend/pkg/api/api.go
I missed some of the otel initialization, now it should be gone
> Replace otel interceptor

- frontend/src/components/pages/connect/Overview.tsx
Fixes an exception thrown on a connector overview in certain cases.
> Connector overview fix

- frontend/src/components/pages/reassign-partitions/ReassignPartitions.tsx
> Provides Reassignment successful message

- frontend/src/components/pages/connect/Connector.Details.tsx
- frontend/src/components/pages/connect/CreateConnector.tsx
- frontend/src/state/connect/state.ts
> Fix connectors secrets

- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/acls/UserDetails.tsx
- frontend/src/components/pages/acls/UserPermissionAssignments.tsx
> Assigned roles in principals table

- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/acls/RoleDetails.tsx
- frontend/src/components/pages/acls/RoleForm.tsx
- frontend/src/components/pages/acls/UserCreate.tsx
- frontend/src/components/pages/acls/UserDetails.tsx
- frontend/src/components/pages/acls/UserPermissionAssignments.tsx
Part 1 of the fixes mentioned in https://github.com/redpanda-data/console/issues/1236
> Rbac fixes

- backend/go.mod
- backend/go.sum
- backend/pkg/api/connect/errors/common_errors.go
This PR adds incompatible redpanda version error to common errors.
> Backend: incompatible redpanda version error

- backend/pkg/console/log_dir_topic.go
- backend/pkg/console/log_dir_topic_test.go
- backend/pkg/console/topic_overview.go
This PR fixes https://github.com/redpanda-data/console/issues/1211 and refactors this code significantly.
> Patch log dir topic

- backend/pkg/kafka/config_helper.go
Currently, when AWS IAM auth fetches token, it only does so once on startup and the same token is reused. This change introduces refresh mechanism by retrieving the token asynchronously when it's needed by the kafka auth system.
Token is internally cached and reused until it expires. Once it expires, a new token is fetched and used.
> backend: refresh aws creds when using iam auth after token expiration

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
https://www.loom.com/share/54fa2582118b454896266df0a04fc544
Fixes #1133
> Adds loading state to a DataTable for messages

- frontend/src/components/pages/schemas/Schema.Create.tsx
> feat: provide JSON example for Schema registry

- frontend/src/components/pages/schemas/Schema.Create.tsx
Fixes https://github.com/redpanda-data/console/issues/1250
> Fixes validation in Schema creation

- frontend/src/components/pages/connect/Connector.Details.tsx
fixes https://github.com/redpanda-data/console/issues/1258
Creating as Draft as I need a confirmation in the issue first
> Disableds log tab in a connector if not relevant topic exists

- backend/pkg/api/api_integration_test.go
- backend/pkg/config/config.go
- backend/pkg/config/proto_topic_mapping.go
- backend/pkg/config/regexp.go
- backend/pkg/config/util_regex.go
- backend/pkg/proto/service.go
- backend/pkg/proto/service_test.go
- backend/pkg/serde/protobuf_test.go
- backend/pkg/serde/service_integration_test.go
Redo of https://github.com/redpanda-data/console/pull/584
> backend: add support for regex topic protobuf mapping

- frontend/src/components/misc/Statistic.tsx
- frontend/src/components/pages/topics/QuickInfo.tsx
Fixes https://github.com/redpanda-data/console/issues/1064
I know @ivpanda wanted to use sentence case elsewhere, so I've used it here as well. Please let me know if I should change some phrasing.
> Information about estimation of the message count

- backend/pkg/config/redpanda_admin_api_tls.go
Fix log message for validating the admin api client config.
> backend: fix config error log message

- .github/workflows/backend-lint-test.yml
- .github/workflows/bsr-push.yml
- .github/workflows/frontend-verify.yml
- .github/workflows/repository-dispatch.yml
fixes: https://redpandadata.atlassian.net/browse/PESDLC-1544
github secrets for this repo have been migrated to aws secretsmanager. this PR uses gha [aws-actions/aws-secretsmanager-get-secrets](https://github.com/aws-actions/aws-secretsmanager-get-secrets) to access the secrets.
> gha: retrieve secrets from aws secretsmanager

- backend/go.mod
- backend/go.sum
> backend: update gorilla/schema

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/pages/topics/CreateTopicModal/CreateTopicModal.tsx
- frontend/src/components/pages/topics/QuickInfo.tsx
- frontend/src/components/pages/topics/Topic.Details.tsx
- frontend/src/components/pages/topics/types.ts
- frontend/src/index.scss
Fixes https://github.com/redpanda-data/console-enterprise/issues/381
> New statistics in a topic detail

- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/admin/Admin.Roles.tsx
Diff looks big because of the spacing, but we've only added padding to 3 places here.
> Adding some table paddings where needed

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
> Padding for search input in a message viewer

- frontend/src/components/pages/overview/Overview.tsx
- frontend/src/state/backendApi.ts
- frontend/src/state/restInterfaces.ts
Fixes https://github.com/redpanda-data/console-enterprise/issues/423
> Remove news from the overview page

- frontend/src/components/pages/schemas/Schema.List.tsx
Fixes https://github.com/redpanda-data/console/issues/1288
> Don't search for an empty string in Schema List

- frontend/src/components/pages/overview/Overview.tsx
Fixes https://github.com/redpanda-data/console/issues/1342
> Correct links to an ACL page

- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/state/ui.ts
Fixes https://github.com/redpanda-data/console-enterprise/issues/363
> Additional RBAC changes

- frontend/src/components/pages/quotas/Quotas.List.tsx
> Quotas column modification

- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/acls/PrincipalGroupEditor.tsx
- frontend/src/components/pages/acls/UserDetails.tsx
- frontend/src/components/pages/acls/UserEdit.tsx
- frontend/src/components/pages/acls/UserPermissionAssignments.tsx
- frontend/src/components/pages/rp-connect/Pipelines.Create.tsx
This fixes a couple issues with the RBAC pages (ACLs, Roles, Permissions List, Users tab).
> frontend: update descriptions and namings

- frontend/src/components/pages/overview/Overview.tsx
> Update Overview Users link

- .github/workflows/bsr-push.yml
- .github/workflows/repository-dispatch.yml
jira: https://redpandadata.atlassian.net/browse/PESDLC-1724
use [oidc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to retrieve secrets
> gha: retrieve secrets using oidc

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
> Provide partition ID and offset in a message detail

- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/acls/PrincipalGroupEditor.tsx
- frontend/src/components/pages/acls/UserCreate.tsx
- frontend/src/components/pages/topics/Tab.Messages/JavascriptFilterModal.tsx
- frontend/src/components/pages/topics/Tab.Messages/index.tsx
These attributes will help the docs team with automated testing and screenshots for docs
> Add test ID attributes

- frontend/src/EmbeddedApp.tsx
Fixes https://github.com/redpanda-data/console-enterprise/issues/422
Needs proper testing
> Removed blocking route change from EmbeddedApp

- README.md
Update available features and remove some outdated information
> readme: update features

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
Fixes https://github.com/redpanda-data/console/issues/1368
> Changes breakpoint in messages list

- frontend/src/components/pages/rp-connect/Pipelines.Details.tsx
fixes https://github.com/redpanda-data/cloudv2/issues/17410
> frontend: use key to filter by pipeline_id

- frontend/src/components/pages/topics/Tab.Partitions.tsx
- Fixes https://github.com/redpanda-data/console/issues/1163
- Styles cleanup
- Icon replacement (MD icon)
> Fixes partition errors + some styles / icon cleanup

- frontend/src/components/pages/acls/UserCreate.tsx
> Show ACL button after user is created

- frontend/src/components/pages/topics/Tab.Messages/index.tsx
~Waiting for Icons definition from @ivpanda~
> Improved start offset select

- frontend/src/components/pages/rp-connect/Pipelines.List.tsx
https://github.com/redpanda-data/console/pull/1424
> frontend: use new pipeline resources

- frontend/src/components/pages/consumers/Group.Details.tsx
- frontend/src/components/pages/consumers/Modals.tsx
https://www.loom.com/share/d912595973b8458d8b432b491570d903
> Workaround for the consumer group radio inputs issue

- frontend/src/components/pages/rp-connect/Pipelines.Create.tsx
- frontend/src/components/routes.tsx
- frontend/src/config.ts
Don't approve/merge this yet without @ivpanda 's approval.
This will probably be redesigned.
> frontend: add docu links to the create page

- frontend/src/state/connect/state.ts
This needs to be properly tested.
> Don't filter properties in getConfigObject

- backend/pkg/config/git_repository.go
- backend/pkg/git/service.go
- docs/config/console.yaml
Supersedes https://github.com/redpanda-data/console/pull/814 and resolves #277
> backend: make git max clone depth configurable

- frontend/src/components/license/licenseUtils.ts
- frontend/src/components/pages/admin/Admin.Licenses.tsx
- frontend/src/components/pages/admin/UploadLicensePage.tsx
- frontend/src/components/pages/overview/Overview.tsx
> Licensing adjustments

- frontend/rsbuild.config.ts
make sure all proxied routes are taken into account in the proxy configuration
> fix(frontend): add all proxied routes

- frontend/src/components/pages/connect/Overview.tsx
- frontend/src/components/pages/rp-connect/Pipelines.Create.tsx
- frontend/src/components/routes.tsx
https://www.loom.com/share/6846900519414934a9984bd909f364bb
> RPCN adjustments

- frontend/src/components/license/LicenseNotification.tsx
- frontend/src/components/license/licenseUtils.ts
- frontend/src/components/pages/admin/AdminPage.tsx
- We show expired licenses only for license type ENTERPRISE
- We show information banner about expiration 15 days before expiration for TRIAL, 30 days before expiration for ENTERPRISE.
> Do not show trial license expiration info

- frontend/src/components/pages/topics/TopicConfiguration.tsx
> Better markup in topic configuration help popup

- frontend/src/components/pages/rp-connect/Pipelines.Create.tsx
- frontend/src/components/pages/rp-connect/Pipelines.Edit.tsx
- frontend/src/components/pages/rp-connect/errors.tsx
> rpcn: pretty print linter errors on update

- frontend/src/components/pages/topics/Topic.Details.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
The current wording "has a leaderless partitions" is weird. This attempts to fix it.
> frontend: improve unhealthy wording

- frontend/src/components/pages/topics/Topic.Details.tsx
- frontend/src/components/pages/topics/Topic.List.tsx
This PR is to quickly fix the grammar issue, I'll fix DRY in another PR.
> Fix the grammar in the partition error message.

- frontend/src/components/debugBundle/DebugBundleLink.tsx
- frontend/src/components/pages/admin/Admin.DebugBundle.tsx
> Design improvements for debug bundle:

- backend/pkg/api/connect/service/license/service.go
- frontend/src/state/backendApi.ts
Fix "Failed to load license info" warning in overview page.
Jira: CONSOLE-71
> Fix license loading

- frontend/src/components/pages/acls/RoleForm.tsx
> Fixes bad provided types in a Role form

- backend/pkg/api/connect/service/license/mapper.go
Make sure license type is mapped correctly in console
> fix(backend): make sure license type is mapped correctly

- frontend/src/components/layout/Content.tsx
- frontend/src/components/license/FeatureLicenseNotification.tsx
- frontend/src/components/license/LicenseNotification.tsx
- frontend/src/components/license/OverviewLicenseNotification.tsx
- frontend/src/components/misc/NullFallbackBoundary.tsx
- frontend/src/components/pages/acls/Acl.List.tsx
- frontend/src/components/pages/admin/UploadLicensePage.tsx
- frontend/src/components/pages/overview/Overview.tsx
- frontend/src/components/pages/reassign-partitions/ReassignPartitions.tsx
- frontend/src/components/pages/rp-connect/Pipelines.Create.tsx
- frontend/src/components/pages/rp-connect/Pipelines.Details.tsx
- frontend/src/components/pages/rp-connect/Pipelines.Edit.tsx
- frontend/src/components/pages/rp-connect/tasks.tsx
This adds a configuration for number of tasks. We'd need to show information on GPU tasks as well, but the API is not providing it.
https://github.com/user-attachments/assets/a64b6f92-87be-4792-8cd1-97661dd42738
> rpcn: add configurable tasks

- frontend/src/components/pages/rp-connect/secrets/Secrets.List.tsx
- frontend/src/config.ts
- frontend/src/state/backendApi.ts
Add pipelines column to secret list page
> rpcn: add pipelines column to secret list page

- frontend/src/components/pages/rp-connect/Pipelines.Create.tsx
add description for task field
> rpcn: add task description

- frontend/src/components/pages/reassign-partitions/Step2.Brokers.tsx
> Replace Kowl with Redpanda Console

- frontend/src/components/pages/transforms/Transforms.Setup.tsx
> frontend: fix typo causing syntax error

- frontend/src/state/backendApi.ts
> Fixes infintie loading when transforms are not configured

- frontend/package-lock.json
- frontend/package.json
- frontend/rsbuild.config.ts
- frontend/src/components/misc/PipelinesYamlEditor.tsx
- frontend/src/config.ts
Add yaml-worker for Monaco in order to allow autocomplete in YAML files
https://github.com/user-attachments/assets/093576ef-5e67-4e0c-87ce-8c173282756f
https://github.com/user-attachments/assets/10d2ea5e-7f1a-4ab6-885f-73a721362d9d
> Yaml monaco editor

- frontend/src/components/pages/acls/Acl.List.tsx
Changes the condition if the request fails
> Change no authorizer configured banner condition

- README.md
> chore: adjusted README

- docs/features/hosting.md
I found another small typo errors in the docs.
> chore: fixed small error

- frontend/src/components/pages/rp-connect/errors.tsx
This provides more useful info e.g. when the pipeline name contains invalid characters.
> rpcn: fix display of validation errors

- frontend/src/components/misc/login.tsx
> Show error message on failed auth methods request

- frontend/src/components/pages/topics/Topic.Produce.tsx
- frontend/src/state/ui.ts
https://github.com/redpanda-data/console/issues/1405
> Feature: Store Most Recently Used Compression Type

- backend/pkg/config/config.go
Add option to opt out of strict YAML validation
> backend: offer opt out for strict config validation

- frontend/src/components/misc/ErrorResult.tsx
- frontend/src/components/pages/secrets/secrets-store-page.tsx
> frontend: Ensure secret store page handles errors

- frontend/src/components/routes.tsx
> frontend: Only show Secrets Store sidebar item in embedded mode

- docs/config/console.yaml
This PR updates the reference config to the latest v3 config.
> config: update reference config for v3

- frontend/src/components/pages/consumers/Group.Details.tsx
- frontend/src/components/pages/consumers/Modals.tsx
- frontend/src/components/pages/rp-connect/Pipelines.Create.tsx
- frontend/src/components/pages/rp-connect/secrets/Secrets.QuickAdd.tsx
- frontend/src/components/pages/topics/Tab.Messages/index.tsx
- frontend/src/components/pages/topics/Topic.Produce.tsx
- frontend/src/state/ui.ts
https://www.loom.com/share/9da6736857de4415b491a9b869c34ef5
> Simplifies the way how we handle URL params in topic detail

- frontend/src/components/pages/acls/Acl.List.tsx
Removes from DOM instead of changing visibility
> Removes info banner from DOM when Roles API is not enabled

- backend/pkg/console/list_messages_integration_test.go
- backend/pkg/console/log_dir_broker.go
- backend/pkg/console/log_dir_topic.go
> chore: fix function name in comment

- frontend/src/components/pages/secrets/create-secret-modal.test.tsx
- frontend/src/components/pages/secrets/create-secret-modal.tsx
- frontend/src/components/pages/secrets/form/secret-schema.ts
- frontend/src/components/pages/secrets/secrets-store-page.tsx
- frontend/src/components/pages/secrets/update-secret-modal.test.tsx
- frontend/src/components/pages/secrets/update-secret-modal.tsx
Add scopes selection to secret creation and update modals
https://github.com/user-attachments/assets/964ce0f4-4a77-4d97-acaf-ded24eb96ea8
> frontend: add scopes selection to secret creation and update modals

- frontend/src/components/pages/schemas/Schema.Details.tsx
- frontend/src/components/pages/schemas/Schema.List.tsx
https://www.loom.com/share/5a78442e54cd45dcb37139f71b324e4f
Fixes:
- Hiding soft-deleted items
- Fixes how route is mounted (this should be addressed properly on a router level, WIP)
- Fixing loading of "Refernced By"
> Provides fixes for schema registry

- frontend/src/components/pages/secrets/create-secret-modal.test.tsx
- frontend/src/components/pages/secrets/create-secret-modal.tsx
- frontend/src/components/pages/secrets/form/secret-schema.ts
- frontend/src/components/pages/secrets/secrets-store-page.tsx
- frontend/src/components/pages/secrets/update-secret-modal.test.tsx
- frontend/src/components/pages/secrets/update-secret-modal.tsx
Backport changes from master for add secret scope to secret create/update modal
> Aa/backport to 2.8

- frontend/src/components/pages/agents/create/templates/http/redpanda-user-and-permissions-form.tsx
- frontend/src/components/pages/topics/create-topic-modal.tsx
- frontend/src/react-query/api/topic.tsx
> frontend: Make sure the internal topics are hidden for AI agents

- backend/pkg/config/tls.go
- backend/pkg/tls/ca.go
- backend/pkg/tls/ca_test.go
- backend/pkg/tls/keypair.go
- backend/pkg/tls/keypair_test.go
- backend/pkg/tls/tls.go
- backend/pkg/tls/tls_test_utils.go
Implement hot reload for TLS certificates, this is meant to be used by clients.
> Ux 225/implement tls reloader

- .github/workflows/buf.yml
No functional change to the checks themselves, just clearer structure, consistent formatting, and automatic label cleanup when branches/tags are pruned.
> ci: refactor Buf CI workflow for clarity and full BSR sync

- backend/pkg/schema/service.go
- Fix atomic refresh for proto schema descriptors to prevent partial state corruption
- Replace incremental updates with complete state replacement for consistency  
- Fix cache key collision vulnerability in GetSchemaBySubjectAndVersion
- Remove unnecessary Go 1.21 loop variable capture pattern
Schema registry degradation occurred when 502 errors during partial fetches caused inconsistent cache state, requiring service restart to recover.
Implement atomic state replacement ensuring either complete success or no changes, preventing partial corruption.
> schema: fix proto schema cache corruption and key collision

- frontend/src/App.tsx
- frontend/src/components/console-sidebar.tsx
- frontend/src/components/layout/Header.tsx
- frontend/src/components/redpanda-ui/components/avatar.tsx
- frontend/src/components/redpanda-ui/components/breadcrumb.tsx
- frontend/src/components/redpanda-ui/components/collapsible.tsx
- frontend/src/components/redpanda-ui/components/sheet.tsx
- frontend/src/components/redpanda-ui/components/sidebar.tsx
- frontend/src/components/redpanda-ui/lib/use-mobile.ts
- frontend/src/components/routes.tsx
Fix for [AI-111](https://redpandadata.atlassian.net/browse/AI-111)
https://github.com/user-attachments/assets/1a25fe3f-0fd9-4d2d-9835-b384e7214ef3
[AI-111]: https://redpandadata.atlassian.net/browse/AI-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> frontend: migrate sidebar for console in self-hosted mode

- frontend/src/components/pages/admin/Admin.DebugBundle.tsx
Backport of https://github.com/redpanda-data/console/pull/1888
This PR introduces two changes to our custom form in the debug bundle:
1. Added units to fields that were previously missing them (size and duration).
2. The form now comes pre-filled with default values, making it easier for customers who only need to change a single field.
> [2.8] UI: Custom debug bundle form improvements

- frontend/src/components/misc/yaml-editor.tsx
- frontend/src/components/pages/remote-mcp/create/metadata/remote-mcp-create-metadata-step.tsx
- frontend/src/components/pages/remote-mcp/create/remote-mcp-create-page.tsx
- frontend/src/components/pages/remote-mcp/create/tools/remote-mcp-create-tools-step.tsx
- frontend/src/components/pages/remote-mcp/details/inspector/remote-mcp-inspector-parameters.tsx
- frontend/src/components/pages/remote-mcp/details/inspector/remote-mcp-inspector-tab.tsx
- frontend/src/components/pages/remote-mcp/details/remote-mcp-configuration-tab.tsx
- frontend/src/components/pages/remote-mcp/details/remote-mcp-connection-tab.tsx
- frontend/src/components/pages/remote-mcp/details/remote-mcp-details-page.tsx
- frontend/src/components/pages/remote-mcp/list/remote-mcp-list-page.tsx
- frontend/src/react-query/api/remote-mcp.tsx
- frontend/src/utils/resource-tiers.ts
Fix for [AI-112](https://redpandadata.atlassian.net/browse/AI-112).
[AI-112]: https://redpandadata.atlassian.net/browse/AI-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> frontend: Improvements to Remote MCP

- CHANGELOG.md
Updates the changelog for the recently released v3.2.2
> chore: update changelog for v3.2.2

- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-vscode.tsx
- frontend/src/components/pages/remote-mcp/details/inspector/remote-mcp-inspector-parameters.tsx
- frontend/src/components/pages/remote-mcp/details/inspector/remote-mcp-inspector-tab.tsx
- frontend/src/components/pages/remote-mcp/json-utils.tsx
- frontend/src/components/pages/remote-mcp/json-view.tsx
- frontend/src/components/redpanda-ui/lib/use-copy.tsx
Fix for [AI-124](https://redpandadata.atlassian.net/browse/AI-124) and RPCN output type support in Remote MCP inspector. Also adds JSON view.
[AI-124]: https://redpandadata.atlassian.net/browse/AI-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> frontend: Support RPCN output type and add JSON mode to MCP inspector

- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-auggie.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-claude-code.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-claude-desktop.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-cline.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-codex.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-cursor.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-gemini.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-manus.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-vscode.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-warp.tsx
- frontend/src/components/pages/remote-mcp/connect-client-guide/remote-mcp-connect-client-windsurf.tsx
- frontend/src/components/pages/remote-mcp/create/tools/remote-mcp-create-tools-step.tsx
- frontend/src/components/pages/remote-mcp/details/inspector/remote-mcp-inspector-tab.tsx
- frontend/src/components/pages/remote-mcp/details/remote-mcp-configuration-tab.tsx
- frontend/src/components/pages/remote-mcp/details/remote-mcp-connection-tab.tsx
- frontend/src/components/pages/remote-mcp/details/remote-mcp-details-header.tsx
- frontend/src/components/pages/remote-mcp/details/remote-mcp-logs-tab.tsx
- frontend/src/components/pages/remote-mcp/details/remote-mcp-tool-button.tsx
- frontend/src/components/pages/remote-mcp/dynamic-json-form.tsx
- frontend/src/components/pages/remote-mcp/json-editor.tsx
- frontend/src/components/pages/remote-mcp/json-view.tsx
- frontend/src/components/pages/remote-mcp/list/remote-mcp-list-page.tsx
- frontend/src/components/pages/remote-mcp/remote-mcp-connect-docs-alert.tsx
- frontend/src/components/pages/secrets/secrets-store-page.tsx
- frontend/src/components/pages/topics/TopicConfiguration.test.tsx
- frontend/src/components/pages/topics/TopicConfiguration.tsx
- frontend/src/components/redpanda-ui/components/form.tsx
- frontend/src/react-query/api/remote-mcp.tsx
Fix for [AI-179](https://redpandadata.atlassian.net/browse/AI-179).
[AI-179]: https://redpandadata.atlassian.net/browse/AI-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> frontend: Improve Remote MCP form validation
