backend/go.mod, backend/go.sum, frontend/src/components/pages/topic/Topic.Config.tsx, frontend/src/components/pages/topic/Topic.QuickInfo.tsx, frontend/src/state/uiState.ts
A user of this lovely tool suggested this, so I created this PR to improve topic quick infos a little bit.
A topic can have one of three possible cleanup policies: delete, compact and a combination of both.
Depending on the policy some topic configuration entries are important while others are irrelevant.
This PR aims at displaying the relevant configs for the different policies in a defined order. Adding or removing favorites should still be working.
Let me know what you think. I might have broken some conventions or made React rookie mistakes. ;)
=> Polish topic quick infos a litte bit

CHANGELOG.md, backend/pkg/api/handle_consumer_group.go, backend/pkg/kafka/connection_helper.go, backend/pkg/kafka/describe_consumer_groups.go, backend/pkg/kafka/list_consumer_groups.go, backend/pkg/kafka/service.go, backend/pkg/kafka/water_mark.go, backend/pkg/owl/consumer_group_overview.go, backend/pkg/owl/topic_consumers.go, frontend/src/state/backendApi.ts
This PR addresses issue #132 and #102 
Especially #102 is resolved on a best effort here as some requests may need to be triggered a second time. Reason for this is that Sarama utilizes several caches which we purge after a request has failed. If this is the case we do not retry the whole request chain as it would likely timeout anyways.
I intend to address this by potentially migrating to a library that exposes more core level functionality. https://github.com/twmb/kafka-go seems to be a good condidate to evaluate for this.
=> Fix consumer group requests

frontend/src/components/misc/Card.tsx, frontend/src/components/misc/ErrorBoundary.tsx, frontend/src/components/pages/schemas/Schema.Details.tsx, frontend/src/state/restInterfaces.ts, frontend/src/state/ui.ts, frontend/src/utils/tsxUtils.tsx
Issue #143 reported an issue when the frontend tried to show "complex" schema types, e.g. non primitive types like number, string, etc.
Since the fields table now potentially requires a lot more width, I also redesigned the layout of Schema.Details.tsx a bit.
=> Fix render error when displaying json types (fixes issue #143)

backend/pkg/kafka/deserializer.go
Messages were sometimes decoded as JSON due to early pattern detection
See #152
=> #152 Give avro deserialization higher priority

CHANGELOG.md, backend/pkg/kafka/deserializer.go
When `value` is empty (the payload has 0 bytes), it should be deserialized to `nil` instead of an empty string (`""`).
This has no effect on any nested values: `{ someProp: "" }` and `{ someProp: null }` etc will all still be deserialized exactly the same as before.
This fixes the very unintuitive filtering for tombstone messages. 
Previously users had to use `value != ""` to filter tombstones (which made no sense),
and now the way to filter tombstones is `value != null` (as expected).
=> Fix null value as empty string

backend/pkg/kafka/config_helper.go
There seems to be a typo that breaks AWS_MSK_IAM authentication.
=> Fix AWS_MSK_IAM configuration handling

backend/pkg/proto/service.go
Fixes https://github.com/cloudhut/kowl/issues/237
Fixed by removing the "/" at the beginning of all file paths and added "/" as import path to the proto parser
=> Support Protobuf Imports

Dockerfile
kowl fails to clone github repositories because of missing new ssh host keys in the image:
`{"level":"fatal","ts":"2021-11-18T07:08:58.014Z","msg":"failed to start owl service","error":"failed to clone git repo: ssh: handshake failed: knownhosts: key mismatch"}`
For reference:
https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> Add new github ssh host keys for ECDSA and Ed25519.

backend/pkg/git/service.go
When using the topic documentation feature, I noticed that Kowl was not pulling topic docs from the configured branch (the branch set with the `OWL_TOPICDOCUMETATION_GIT_REPOSITORY_BRANCH` docker environment variable. Here's the behavior I was seeing:
When I started Kowl, I had a git repository like this:
```
[branch: main]
- topic1.md
[branch: new-branch]
- topic1.md
```
Here are the contents of each of the files:
```
[branch: main] topic1.md
This is my documentation for topic 1
main
[branch: new-branch] topic1.md
This is my documentation for topic 1
new-branch
```
The `OWL_TOPICDOCUMETATION_GIT_REPOSITORY_BRANCH` variable was set to `"new-branch"`. Sure enough, after Kowl cloned the git repository, I saw this message in the logs:
```json …
```
=> Fix: topic docs: pull from specified branch

frontend/src/utils/tsxUtils.tsx
Fixes #319 
Set the `en` default locale for everyone so no weird things happen when pretty printing some big numbers such as offsets.
=> Use en as default locale for number separators

frontend/src/components/pages/topics/Tab.Docu.tsx
Resolves #323.
Looks like we were missing `{children}` inside of the `<code>` tags. That would definitely explain why they were empty.
Additionally, code blocks were wrapped in two `<pre>` tags. The HTML looked something like this:
```html
<pre>
<pre style="...">
<code>...</code>
</pre>
</pre>
```
This made code blocks with highlighting look... blocky.
Using `PreTag="div"` will change the inner `<pre>` tag into a `<div>`. Now we have less "blocky" visuals:
([Reference docs](https://github.com/remarkjs/react-markdown#use-custom-components-syntax-highlight))
=> Fix: topic docs: render code blocks

frontend/src/components/pages/topics/Tab.Partitions.tsx
The partitions tab in the topics page is meant to show the
current Leader as well as all the replica brokers of a given partition.
The responsible component so far always picked the first broker in
the replica set as the Leader.
This is usually correct, on partition creation the first broker in the replica
set is denoted as Leader, this broker is the "preferred Leader" for the
given partition and the cluster (depending on the configuration) tends to
re-elect the preferred Leader.
Unfortunately, the preferred Leader is not always available,
it can be the case that that the preferred broker is offline and another
broker is elected as Leader.
The current implementation does not properly track the actual leader,
instead it shows the preferred Leader. It also doesn't show which
brokers are …
=> Fix partition tab leader tracking and status visualization

backend/pkg/api/handle_kafka_connect.go, backend/pkg/connect/config.go, backend/pkg/connect/service.go, docs/config/kowl-business.yaml, docs/config/kowl.yaml
6 seconds is not enough when Kafka Connect has A LOT of connectors
=> Use config vars instead of hardcoded timeouts

backend/pkg/kafka/api_version.go
Remove illegal space character from Kafka get API versions request (#390).
=> Fix Kafka GetAPIVersions

frontend/src/components/pages/topics/Tab.Messages/index.tsx
Fix 'Delete Records' tooltip title in order to display a proper message (#392).
=> Fix 'Delete Records' title when disabled

frontend/src/colors.ts, frontend/src/components/pages/topics/Tab.Messages/index.tsx, frontend/src/index.scss, frontend/src/index.tsx, frontend/src/utils/createAutoModal.tsx, frontend/src/utils/tsxUtils.tsx
Fixes colors for:
* Topics value tab underline
* Hide statistics bar icon
* Topic created 'success' icon
* Sweep through index.scss and manually replace blue-brand colors with orange-brand color.
This is likely not exhaustive, as there are colors still written inside component files.  It should catch 90% of uncaught colors.  As we migrate towards using our own component library we will uncover the remaining colors, but for now this should be satisfactory.
=> front-end: fix missing brand colors

backend/pkg/kafka/config_sasl_aws_iam.go
The RegisterFlags mistakenly assigns the secret key to the access key causing issues when using IAM Authentication
=> Fix the assignment flag of secretKey

helm/console/templates/deployment.yaml, helm/console/templates/secret.yaml, helm/console/values.yaml
This commit adds support for a embedding a github basic auth password as a kubernetes `secret` in the helm chart.
Before this change, when setting up a git repository as a protobuf registry for
protobuf deserialization, you could provide basic auth credentials through the helm chart.
However you could not provide the secret to the helm chart without exposing it in a `configmap` resource.
After this change, you can now provide it to the helm chart via:
```yaml
secret:
kafka:
protobufGitBasicAuthPassword: <MYPASSWORD>
```
The change follows the pattern already present in the helm chart for console secrets:
1. add the value to the `secret` resource
2. map it the value from the `secret` to an environment variable using the `deployment` resource.
3. the environment variable name used is the …
=> helm: git credentials secret

frontend/src/state/backendApi.ts
**cover letter**:
simply extend the queries for ACLs in topic and consumer-groups.
I thought about doing it in the default query, but I like the idea of passing the value explicitly.
=> fix: update get ACLs query on topics and consumer-groups

CONTRIBUTING.md
This PR updates wording of the contributing doc to say Redpanda Console instead of Kowl because of [rename](https://redpanda.com/blog/redpanda-acquires-cloudhut-kowl-data-streaming-kafka-ui).
=> update CONTRIBUTING.md for Redpanda Console rename

SECURITY.md
This PR updates wording of the security doc to say `Redpanda Console` instead of `Kowl` because of [rename](https://redpanda.com/blog/redpanda-acquires-cloudhut-kowl-data-streaming-kafka-ui).
Also changed the contact email from info@cloudhut.dev to security@redpanda.com to line up with the [email mentioned in redpanda repo](https://github.com/redpanda-data/redpanda/blob/v22.2.2/SECURITY.md).
=> update SECURITY.md for Redpanda Console rename

docs/installation.md
Updating installation.md Kubernets section to match official documentation https://docs.redpanda.com/docs/console/installation/#kubernetes, current helm chart link was linking to the old console (kowl)
=> feat: update installation.md

frontend/src/injectApp.tsx
return react-dom/client Root on injectApp function to allow the user to unmount the remote app
=> feat(frontend): extend injectApp to return root container

helm/examples/console-enterprise.yaml
if not specified you get error:
```json
{"level":"fatal","msg":"failed to validate config","error":"failed to validate enterprise config: failed to validate RBAC config: RBAC must be enabled until a RBAC-less mode is supported in Redpanda Console"}
```
Source: https://docs.redpanda.com/docs/console/reference/config/
=> `rbac.enabled` is `false` by default

backend/pkg/config/proto.go, backend/pkg/git/util.go, backend/pkg/proto/service.go
add new config parameter proto.importPaths.
if import paths are configured, these paths are all treated as roots. if not configured, the already existing behavior is preserved.
in addition, if git.basePath is empty / "." (default), the dot from file extensions is dropped, resuling in paths where the dot of the file extension is missing. the dot is now not stripped anymore.
=> proto: allow multiple import paths

frontend/src/components/misc/UserPreferences.tsx, frontend/src/components/misc/buttons/buttons.module.scss, frontend/src/components/misc/buttons/data-refresh/Component.tsx, frontend/src/state/ui.ts
Add an "Auto Refresh" button next to the "Force Refresh" button:
When pressed, the page will be automatically force refreshed every `X` seconds where `X` can be configured in the "User Preferences" panel:
When the auto refresh is active, the "Auto Refresh" and "Force Refresh" button will be displayed with pulsating and rotation animations respectively:
Pressing the button again disables the auto refresh.
=> Auto Refresh button

helm/README.md, helm/console/Chart.yaml
Deprecate the helm chart in this repository in favor of [redpanda-data/helm-charts](https://github.com/redpanda-data/helm-charts)
=> chart: deprecate the helm chart from this repo

backend/pkg/proto/service.go, backend/pkg/proto/service_test.go
When decoding a binary message that by accident has a valid starting sequence we may ended up with a slice allocation that is too large. This commit will mitigate the problem by returning an error in all cases where we would want to allocate more than 128 message type ids.
=> backend: Fix panic when deserializing schema registry wrapper

backend/pkg/connect/guides/s3_sink_connector.json
Making aws.s3.region a basic option for S3 sink connector, adding aws.s3.bucket.check definition.
=> Making aws.s3.region a basic option for S3 sink connector

backend/pkg/api/util_cors.go
We used to compare the URL host against the configured allowed origin. This doesn't work because the host omits the scheme whereas the configured allowed origin
does not. Hence the result was that the requester's origin does not match any of the configured allowed origin, unless we also omit the scheme in the configuration.
=> backend: Fix origin check func

frontend/src/components/misc/KowlJsonView.tsx, frontend/src/components/misc/UserPreferences.tsx, frontend/src/state/ui.ts
See https://github.com/redpanda-data/console/issues/607 for discussion of feature.
I couldn't think of a sensible way to implement the ability to set a default `collapsed` setting from the config.yaml on the backend, so I skipped that.
=> frontend: Add user preference for collapsing JSON objects

backend/pkg/config/connect_cluster_tls.go, backend/pkg/config/redpanda_admin_api_tls.go, backend/pkg/schema/client.go
The schema registry connectivity may fail with a
x509: certificate signed by unknown authority error because we used to initialize an empty cert pool that is passed to the TLS config. Instead of always initializing the cert pool, we should pass a nil cert pool if no CA has been specified so that the clients will implicitly load the system cert pool.
=> backend: Fallback to system cert pool if no ca configured

backend/pkg/api/middlewares.go, backend/pkg/api/routes.go
The middleware does still the same, but this refactoring simplifies the code for better maintainability.
=> backend: Refactor base path middleware

CHANGELOG.md, backend/go.mod, backend/go.sum, backend/pkg/api/handle_brokers.go, backend/pkg/api/handle_consumer_group.go, backend/pkg/api/handle_kafka_connect.go, backend/pkg/api/handle_operations.go, backend/pkg/api/handle_schema.go, backend/pkg/api/handle_topic_documentation.go, backend/pkg/api/handle_topics.go, backend/pkg/api/handle_users.go, frontend/src/components/pages/connect/Cluster.Details.tsx, frontend/src/components/pages/connect/Connector.Details.tsx, frontend/src/components/pages/connect/CreateConnector.tsx, frontend/src/components/pages/connect/Overview.tsx, frontend/src/components/pages/consumers/Group.Details.tsx, frontend/src/components/pages/consumers/Group.List.tsx, frontend/src/components/pages/topics/Tab.Consumers.tsx, frontend/src/components/pages/topics/Topic.List.tsx, frontend/src/state/backendApi.ts
Prior to this PR some requests & pages failed to load in Console. For instance special characters like a slash are allowed in Consumer groups but were not supported due to missing escaping. This PR escapes & unescapes all URL & query parameters
=> Escape & unescape all url & query parameters

backend/pkg/console/overview.go
Omit the redpanda version if we aren't talking to a Redpanda cluster with admin api enabled.
=> backend: Include redpanda version only if set

backend/pkg/api/middlewares.go
We stripped the prefix properly, but did not call the next handler in the request stack.
=> backend: Fix basepath middleware

.github/workflows/kics-iac.yml
don't scan test code with KICS to reduce noise
=> exclude tests from KICS scans

backend/pkg/config/kafka.go, backend/pkg/config/kafka_startup.go, backend/pkg/kafka/backoff.go, backend/pkg/kafka/backoff_test.go, backend/pkg/kafka/service.go
Fixes #663
Sample configuration:
```yaml
kafka:
startup:
maxRetries: 0 # unlimited retries
retryInterval: 2s
maxRetryInterval: 15s
backoffMultiplier: 1.8
```
defaults to:
```go
k.MaxRetries = 5
k.RetryInterval = time.Second
k.MaxRetryInterval = 60 * time.Second
k.BackoffMultiplier = 2
```
=> backend: Add config to configure retries on startup

backend/pkg/connector/guide/jdbc_source.go
'table.names.qualify' property will be available in next JDBC source connector release
=> connectors: added 'table.names.qualify' property to jdbc source connector guide

backend/pkg/api/api_integration_test.go, backend/pkg/api/handle_topic_create_integration_test.go, backend/pkg/api/handle_topics_integration_test.go
**Changes**
Adds tests for get topics route `GET /api/topics`. 
Minor refactoring of common testing hooks into `api_integration_test.go` and added ability to specify return values into the mocked hooks.
=> Backend get topics tests

backend/pkg/api/api_integration_test.go, backend/pkg/api/handle_topic_create_integration_test.go, backend/pkg/api/handle_topics_integration_test.go, backend/pkg/console/describe_quotas.go, backend/pkg/kafka/describe_quotas.go, backend/pkg/kafka/mocks/kafka.go, taskfiles/backend.yaml
This PR adds goimports to the `backend:fmt` task. The changes after running this commit have been put into a separate commit.
=> Add goimports to fmt task

backend/pkg/kafka/log_dir.go, backend/pkg/kafka/log_dir_test.go
Clusters that support tiered storage, each broker may report the same shared log dir information for the same partition. Thus, for logdirs that are mounted under `remote://` we de-duplicate reported log dirs for the same partition. In the end we will attach this log dir information to a single broker, so that the total size will still be returned.
=> backend: de-dupe remote log dirs

frontend/src/components/pages/connect/Connector.Details.tsx, frontend/src/components/pages/connect/dynamic-ui/components.tsx, frontend/src/components/pages/topics/Tab.Messages/index.tsx, frontend/src/state/connect/state.ts
- remove "View JSON Config" button in connector details
- add a new "JSON" mode of viewing config of connectors as an alternative to the "Form" view. 
In standalone mode the JSON mode can also be used to edit (not just view) the config and add/modify config properties arbitrarily
- change what buttons are shown (and when) in connector details:
- Pause/Resume will show for states 'RUNNING', 'PAUSED'
- Restart will now always be present (so, in any state)
=> Connectors 717

frontend/src/components/pages/topics/Tab.Messages/index.tsx
Fixes #724 
I'm not a frontend dev, but I think I managed to implement this one. 
I removed the condition that hides the dropdown when the value is `null`. Instead, there is now a condition that disables the 'Copy value' and 'Copy key' menu item based on whether the key or value is null respectively. This also means that 'Copy epoch timestamp' (and 'save to file') is always available in the dropdown menu.
It seems to work for me locally. 
Please let me know if there are any comments or requests for changes.
=> frontend: enable copy dropdown also when record value is null

backend/pkg/console/service.go
Previously the kafka service wasn't always started. That was a bug introduced as part of the refactorings where the kafka service was moved as a member of the console service. This would cause protobuf schemas to not be pulled anymore.
=> backend: always start kafka service

backend/pkg/api/api_integration_test.go, backend/pkg/connector/interceptor/mirror_hook.go, backend/pkg/connector/interceptor/mirror_hook_test.go
Add `org.apache.kafka.connect.converters.ByteArrayConverter` as default `header.converter` for MirrorSourceConnnector.
=> Make bytes default header converter for MirrorSourceConnector

backend/go.mod, backend/go.sum
Due to an issue in the latest protoreflect lib a panic was thrown when parsing protobuf schemas that used an import.
Ref: https://github.com/jhump/protoreflect/issues/564
=> backend: downgrade protoreflect to v1.14

.github/workflows/backend-lint-test.yml
To fix failing integration tests due to
https://github.com/golang/go/issues/61431
https://github.com/testcontainers/testcontainers-go/issues/1359
=> backend: pin verify action to go 1.20.5

backend/pkg/schema/service.go, backend/pkg/schema/service_test.go
When Console tries to deserialize a protobuf message in schemaregistry encoding it first tries to decode it as avro message. If that fails a warn message is logged. This PR returns early from deserializing it in avro when it notices that the pulled schema is of type protobuf.
=> backend: remove warning failed to parse avro schema

docs/README.md
The link in the documentation is still pointing to the deprecated charts repository, so I updated it.
=> Update link to Helm chart repo in installation docs

backend/pkg/api/handle_kafka_connect_integration_test.go, backend/pkg/kafka/deserializer_integration_test.go
The integration tests for connectors have been flaky (mostly failing) for me, because the connector hasn't produced the number of expected records in time.
=> Fix flaky integration tests

frontend/package-lock.json, frontend/package.json, frontend/src/state/backendApi.ts, frontend/src/utils/utils.ts
Manually brings in ef7801a to release branch.
Tested by checking out `release-2.3` branch and I was able to reproduce the rendering issue with the JavaScript stack trace.
With this change the messages rendered fine.
=> frontend: fix base64 decoding of 'utf8WithControlChars'

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/misc/NoClipboardPopover.tsx, frontend/src/components/misc/buttons/data-refresh/Component.tsx, frontend/src/components/pages/connect/helper.tsx, frontend/src/components/pages/consumers/Group.Details.tsx, frontend/src/components/pages/consumers/Modals.tsx, frontend/src/components/pages/reassign-partitions/Step1.Partitions.tsx, frontend/src/components/pages/schemas/Schema.Details.tsx, frontend/src/components/pages/topics/Tab.Messages/PreviewSettings.tsx, frontend/src/components/pages/topics/Tab.Messages/index.tsx, frontend/src/components/pages/topics/Tab.Partitions.tsx, frontend/src/components/pages/topics/Topic.Details.tsx, frontend/src/components/pages/topics/Topic.List.tsx, frontend/src/components/pages/topics/TopicConfiguration.scss, frontend/src/components/pages/topics/TopicConfiguration.tsx, frontend/src/index.scss
Moved all Popover components instances to use the new Redpanda Popover component. The new component allows for props to specify the title and content of the popover.
~*** _PR is dependent on [this PR](https://github.com/redpanda-data/ui/pull/339) from the UI library. Do not merge until `package.json` has been updated to that version._~ (now updated)
=> ui: Migration - Popover Component

backend/pkg/config/filesystem.go
Fixed load yaml config: 'kafka.protobuf.FileSystem' has invalid keys: "skipHiddenFiles"
```
{"level":"fatal","msg":"failed to load yaml config","error":"failed to unmarshal YAML config into config struct: 1 error(s) decoding:\n\n* 'kafka.protobuf.FileSystem' has invalid keys: skipHiddenFiles"}
```
the yaml:
The root issue: https://github.com/redpanda-data/console/issues/810
=> Fixed load yaml config: 'kafka.protobuf.FileSystem' has invalid keys: "skipHiddenFiles"

frontend/src/components/pages/consumers/Group.Details.tsx
This PR fixes the Tag regression.
Before:
s the regression in master.
After:
=> fix: tags regression fixed

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/misc/ErrorBoundary.tsx, frontend/src/components/misc/HideStatisticsBarButton.tsx, frontend/src/components/misc/KowlJsonView.tsx, frontend/src/components/misc/UserPreferences.tsx, frontend/src/components/pages/acls/Acl.List.tsx, frontend/src/components/pages/acls/PrincipalGroupEditor.tsx, frontend/src/components/pages/connect/CreateConnector.tsx, frontend/src/components/pages/connect/helper.tsx, frontend/src/components/pages/reassign-partitions/ReassignPartitions.tsx, frontend/src/components/pages/reassign-partitions/components/ActiveReassignments.tsx, frontend/src/components/pages/schemas/Schema.Details.tsx, frontend/src/components/pages/topics/DeleteRecordsModal/DeleteRecordsModal.tsx, frontend/src/components/pages/topics/Tab.Messages/index.tsx, frontend/src/components/pages/topics/Topic.List.tsx, frontend/src/components/pages/topics/TopicConfiguration.tsx, frontend/src/state/backendApi.ts, frontend/src/utils/tsxUtils.tsx, frontend/src/utils/utils.ts
This PR migrates the message and toast component to use Chakra's Toast implementation.
WIP: I'm in a middle of testing, but I think this PR can be already looked at.
- Chakra's Toast is implemented using a hook, so a functional component is required. 
1. On a couple of places, I've migrated the component to a FC, this needs to be tested
2. At the same time, I wanted to minimise the number of changes, so on some places I've left React as a component class and left a comment about a future migration. In these cases, I use Chakra's standalone toasts.
3. A couple of messages are not migrated, because of the problem with Modals. Chakra's toast and Ant design modals doesn't play well together, because of ChakraProvider that kills the toasts on its removal. This will be addressed together with a …
=> feat: toast component migration

backend/pkg/connector/patch/mongo.go
The importance settings for the MongoDB connectors configs were set inside a method and lost, resulting in some config options missing in the connector creation basic form.
Returning the updated `model.ConfigDefinition` from the method to fix the importance settings.
=> Fix setting importance of MongoDB connectors config options

frontend/src/components/misc/Wizard.tsx, frontend/src/components/pages/reassign-partitions/ReassignPartitions.tsx
Stepper component was used in 2 places:
Reassign partitions:
And as part of Create Connector Wizard, where it actually didn't show up, so we just removed it.
=> Migrate Stepper component

README.md
This Pull Request fixes a typographical error in the README.md file.
Corrected " enconding " to " encoding " in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.
=> Remove typo enconding 

backend/pkg/connector/guide/iceberg_sink.go, backend/pkg/connector/interceptor/iceberg_sink_hook.go, backend/pkg/connector/interceptor/interceptor.go
This fixes missing `iceberg.catalog.*` properties in the Iceberg sink connector guide.
=> Iceberg guide fix

frontend/src/components/pages/acls/Acl.List.tsx, frontend/src/components/pages/connect/helper.tsx, frontend/src/components/pages/consumers/Group.Details.tsx, frontend/src/components/pages/quotas/Quotas.List.tsx, frontend/src/components/pages/reassign-partitions/Step3.Review.tsx, frontend/src/components/pages/schemas/EditCompatibility.tsx, frontend/src/components/pages/schemas/Schema.List.tsx, frontend/src/components/pages/topics/Tab.Config.tsx, frontend/src/components/pages/topics/Tab.Docu.tsx, frontend/src/components/pages/topics/Tab.Messages/index.tsx
Empty component migrated to Chakra
- In some places where it semantically make sense, we replaced `Empty` with `Result` - especially where backend returns 403.
- Our `Empty` component in `@redpanda-data/ui` doesn't support `extra` and secondary `description`  + it has two modes based on a code so it's not easy to add these params. That's why we solve these usecases with `VStack` for now, and we should re-think refactoring of `Empty` in the future.
Note: We've added a gap for a buttons in a VStack scenario. However, this will be DRYed later during refactor.
=> Migrated Empty component to Chakra

frontend/src/components/pages/topics/TopicConfiguration.scss, frontend/src/components/pages/topics/TopicConfiguration.tsx
The video shows the new implementation with our Chakra components, in the second part of the implementation, the old UX is shown for comparison.
https://www.loom.com/share/625caa2c0c9047129c2548cdb3c1641d
- This PR migrates almost all Chakra components from TopicConfiguration
- We have slightly changed some components to be consistent with Chakra's components library
- After consulting with a backend, MULTI_SELECT is removed as an option
=> Migrated TopicConfiguration fields to Chakra

frontend/src/components/pages/connect/Connector.Details.tsx, frontend/src/components/pages/connect/CreateConnector.tsx, frontend/src/components/pages/connect/dynamic-ui/components.tsx, frontend/src/components/pages/overview/Overview.tsx, frontend/src/components/pages/reassign-partitions/components/ActiveReassignments.tsx, frontend/src/utils/tsxUtils.tsx
This PR Migrates `Skeleton` to Chakra's `SkeletonText`. I think the look'n'feel is very similar to the original.
=> Migrates Skeleton component from AntD

frontend/src/components/pages/acls/Acl.List.tsx, frontend/src/components/pages/acls/CreateServiceAccountEditor.tsx
This dialogue improves the user creation modal. In a follow-up PR the success modal will be improved @ivpanda 
Changes:
- Add clipboard button to copy the password
- Use new Formfield
- Improve field & form validation
=> frontend: improve user creation modal

frontend/src/components/layout/Content.tsx, frontend/src/index.scss
Before:
After:
Semantically it's a warning, also in the code it's called a warning so I've changed the type.
=> Better license expiration warning

backend/pkg/kafka/deserializer.go
Currently msgpack-encoded message is passed as string into JS VM. So it does not allow filtering by object fields.
This little fix changes msgpack object to be the same as JSON, XML and other encoded messages.
=> fix msgpack filtering

backend/pkg/api/hooks.go, backend/pkg/api/routes.go
This PR allows to inject HTTP middlewares (e.g. for auth) via the ConfigConnectRPC hook.
=> backend: add middleware support to ConfigConnectRPC hook

frontend/src/components/pages/topics/Tab.Messages/index.tsx, frontend/src/utils/tsxUtils.tsx
The timestamps of kafka messages passed around got changed from seconds to milliseconds since unix epoch time, with #184
Adjusts some leftovers from that change; in particular, the displayed text in the UI that was still showing the raw format as "Unix Seconds"
=> Match display-text to unit of message timestamps (#923)

proto/buf.yaml
this enables us to maintain the protos in the Buf Schema Registry at https://buf.build/redpandadata/dataplane
=> proto: add name to buf.yaml to enable BSR

backend/pkg/api/connect/interceptor/endpoint_check.go, backend/pkg/config/console_api.go
Prior to this commit there was some postprocessing inside the validate() function going on. Instead of converting a slice to a map inside the validate and storing it as a member, we now added a Getter function for this.
=> backend: don't postprocess config in validate call

backend/pkg/connector/guide/mongo_source.go, backend/pkg/connector/interceptor/mongo_hook.go
Added `producer.override.max.request.size` property to Mongo source connector UI
=> connectors: added `producer.override.max.request.size` property to Mongo source connector UI

frontend/src/components/pages/acls/Acl.List.tsx, frontend/src/components/pages/acls/CreateServiceAccountModal.tsx
This commit uses a new modal for creating new users. Visually only the user confirmation modal is different and more in line with the new Redpanda theme.
https://github.com/redpanda-data/console/assets/23424570/7019e517-f11f-469e-aed4-a19221b9d4d4
=> frontend: update modal to create new user

backend/pkg/connector/interceptor/mongo_hook.go
For local URIs, without username and password, the MongoDB `connection.uri` wasn't populated from the `connection.url` field.
=> Fix construction of `connection.uri` for MongoDB source connector

backend/pkg/connector/guide/mongo_source.go
... as the connector does not support running multiple tasks.
=> Remove `tasks.max` for MongoDB source connector

frontend/src/state/backendApi.ts
We provide `startTimestamp` to the `ListMessagesRequest` in this PR which should fix https://github.com/redpanda-data/console/issues/966
=> Search messages based on a timestamp

backend/pkg/api/api_integration_test.go, backend/pkg/api/connect/interceptor/error_log.go, backend/pkg/api/hooks.go, backend/pkg/api/routes.go
Whenever a connect handler returns an error it is
currently not logged. However, usually this should be of interest. This PR adds an interceptor that
always logs returns errors by any connect handler.
=> backend: add interceptor that logs connect erors

backend/pkg/config/server.go
For the List Messages endpoint that no longer uses Websockets we have to upper the global write timeout so that the ListMessages streaming response can
take longer than the current default of 30s.
=> backend: increase default server write timeout

frontend/src/components/pages/topics/Topic.List.tsx
Serverless does not create internal topics under the hood and this settings prevented users to see topics beginning with underscore (_), even if they could create them.
=> serverless: do not force hiding internal topics

frontend/src/components/pages/schemas/Schema.Create.tsx
This is a quick fix, but I think we should consider moving forms & validation to react-hook-form for consistency
=> Make key/value required in schema validation when topic is selected

backend/pkg/api/routes.go, backend/pkg/config/server.go
It's enabled by default for backward compatibility, but it can now be turned off and enabled on demand.
=> pprof: allow to disable REST handler

backend/pkg/api/routes.go
This caused a panic in our install. Internal router config should be applied once and after the middleware config.
=> pprof: fix configuration of internal routes

frontend/src/components/pages/topics/Tab.Messages/index.tsx, frontend/src/state/ui.ts
With this PR, we hide `Value Size` and `Key Size` in a message viewer by default.
=> Show selected properties in a message viewer by default

backend/pkg/api/connect/integration/user_test.go
In the integration test introduced in https://github.com/redpanda-data/console/pull/1067 we cleanup the created resources after every individual test. Instead of deleting all created users, we accidentally deleted the same user twice.
=> Fix user integration test resource cleanup

backend/pkg/console/list_messages_integration_test.go, backend/pkg/serde/service.go, backend/pkg/serde/service_integration_test.go, backend/pkg/serde/text.go, backend/pkg/serde/text_test.go
Another fix for #1073
in text serde set deserialized payload to string rather than bytes
=> backend: text decoding deserialized payload should be string

frontend/src/components/pages/topics/Tab.Consumers.tsx, frontend/src/components/pages/topics/Tab.Partitions.tsx
Persists information about Topic Consumers and Topic Parititons table to a local storage.
In order to take advantage of `usePaginationParams` hook, we needed to convert these Classes to FC.
=> Persist consumers and partitions size in localstorage

frontend/src/components/pages/topics/Tab.Consumers.tsx, frontend/src/components/pages/topics/Tab.Messages/index.tsx, frontend/src/components/pages/topics/Tab.Partitions.tsx, frontend/src/components/pages/topics/Topic.List.tsx, frontend/src/hooks/usePaginationParams.test.ts, frontend/src/hooks/usePaginationParams.ts
Fixes https://github.com/redpanda-data/console/issues/1104
=> Limit last page to the last existing page in the table

backend/pkg/connector/guide/mirror_source.go
Add `How out-of-sync a remote partition can be before it is resynced` to MirrorSourceConnector guide.
=> Add `offset.lag.max` advanced property to MM2 guide

backend/pkg/api/handle_schema_registry.go, backend/pkg/api/handle_schema_registry_test.go
=> backend: getSubjectFromRequestPath trim query suffix if present

frontend/src/components/layout/Header.tsx, frontend/src/components/misc/buttons/buttons.module.scss, frontend/src/components/pages/Page.ts, frontend/src/components/pages/acls/Acl.List.tsx, frontend/src/components/pages/acls/CreateServiceAccountModal.tsx, frontend/src/components/pages/connect/Cluster.Details.tsx, frontend/src/components/pages/connect/Connector.Details.tsx, frontend/src/components/pages/connect/Overview.tsx, frontend/src/components/pages/consumers/Group.Details.tsx, frontend/src/components/pages/consumers/Group.List.tsx, frontend/src/components/pages/reassign-partitions/Step1.Partitions.tsx, frontend/src/components/pages/schemas/EditCompatibility.tsx, frontend/src/components/pages/schemas/Schema.Details.tsx, frontend/src/components/pages/schemas/Schema.List.tsx, frontend/src/components/pages/topics/Topic.Details.tsx, frontend/src/components/pages/topics/Topic.List.tsx, frontend/src/components/pages/topics/Topic.Produce.tsx, frontend/src/index-cloud-integration.scss, frontend/src/index.scss, frontend/src/state/uiState.ts, frontend/src/utils/utils.test.ts, frontend/src/utils/utils.ts
1. I think having it in the breadcrumb is a good thing when it comes to consistency. We currently have the detail items there for all the pages I know of.
2. I think it's however OK to cut it when needed (we have no other choice). I've worked on a prototype that takes all the possible space and adds `...` once needed.  (Please note that the whitespace at the end is needed for the refreshing text, if we could get rid of that it could go til the end).
However in this scenario we would need to add `copy to clipboard` icon so that users can copy it if it's too long. Sth like github does 
In the tables I prototyped the solution that would take `n` number of lines before it shows `...` 
WDYT?
=> Better handling of long names in the tables & breadcrumbs

frontend/src/state/backendApi.ts
SchemaRegistries such as apicurio or karapace do not support the /mode endpoint. When opening the schema registry pages they failed to load because this request failed. The response to this request should not be mandatory. This is changed with this PR.
=> frontend: still render schema pages if mode request errors

frontend/src/components/pages/schemas/Schema.Create.tsx
Fixes #1153
https://www.loom.com/share/1e082725cb7041f78449ccfbe84df288?from_recorder=1&focus_title=1
In this case I decided to show the modal as well, because the error message shown in a toast that disappears is quite unusable. cc @ivpanda
=> Shows schema validation error on submit

frontend/src/components/pages/connect/Overview.tsx, frontend/src/state/ui.ts
https://www.loom.com/share/3a86ac9ea26443bfbc25ef2787fc6b57?from_recorder=1&focus_title=1
Fixes https://github.com/redpanda-data/console/issues/1135#event-11938716242
=> Adds search to saerch connectors overview

backend/pkg/console/list_acls.go, backend/pkg/console/list_acls_integration_test.go
Adds `principalType` to the response to the `GET /acl` endpoint.
The type can be one of several predefined values.
Also adds `principalName` to the response. This is just the value of the `principal` with the type prefix removed.
=> backend: add principal type and name to list acls operation

backend/pkg/api/connect/integration/api_suite_test.go, backend/pkg/api/routes.go
If the observer interceptor intercepts requests
that are already aborted by previous interceptors
such as the validation interceptor, we will report the wrong statuses.
=> backend: move observer interceptor to the first place

backend/pkg/console/alter_configs.go, backend/pkg/console/broker_config.go, backend/pkg/console/create_topic.go, backend/pkg/console/delete_acls.go, backend/pkg/console/delete_topic.go, backend/pkg/console/errors.go, backend/pkg/console/errors_test.go, backend/pkg/console/list_acls.go
To date we do not propagate the dynamic server error message in case it's part of the Kafka response. For the new Connect API we already do so, but not for the legacy REST API.
=> Propagate dynamic error messages

frontend/src/state/backendApi.ts
This fixes UI rendering if schema types endpoint doesn't exist in schema registry (mostly old registries)
```
{"level":"error","ts":"2024-05-08T17:03:08.003Z","msg":"Sending REST error","route":"/api/schema-registry/schemas/types","method":"GET","status_code":502,"remote_address":"10.3.1.11","public_error":"Failed to retrieve schema registry types from the schema registry: get schema types failed: Status code 404","error":"get schema types failed: Status code 404"}
```
Very similar PR to [this](https://github.com/redpanda-data/console/pull/1154).
=> fix: still render the UI if failed to refresh schema types

frontend/src/state/connect/state.ts
`// PUT "/kafka-connect/clusters/{clusterName}/connector-plugins/{pluginClassName}/config/validate"` 
seems to ignore some of the properties which are then not stored in a local state.
Ideal solution would be for this call to return all received properties instead of ignoring them, alternatively this fix should hopefully solve the problem that the properties unsupported in the UI are stripped.
This needs proper testing before merging. So far I've tested my self and it works.
FYI: The reason why it worked in the Create mode is that if the user chooses the JSON view, all validations are ignored and plain JSON is sent to the backend.
fixes https://github.com/redpanda-data/console-enterprise/issues/350
=> Provide default values in the init for a connector

backend/pkg/api/connect/integration/api_suite_test.go, backend/pkg/api/connect/interceptor/error_log.go, backend/pkg/api/hooks.go, backend/pkg/api/hooks/hooks.go, backend/pkg/api/routes.go
Adds `InitConnectRPCRouter` hook that goes at the start of the connect routes to be able to properly wrap all the middleware and routes that come afterwards.
=> backend: add hooks for init router to enable better logging

frontend/src/components/pages/acls/PrincipalGroupEditor.tsx
Fixes https://github.com/redpanda-data/console-enterprise/issues/399
I've extended it but as @rikimaru0345 pointed out it might still not be enough to read all text, it really depends on a selector. @ivpanda in that case I guess we will need a different UX solution, but we should learn about how long the data is first.
=> Fixes long names in PrincipalGroupEditor

backend/pkg/console/endpoint_compatibility.go, backend/pkg/redpanda/service.go
When no WASM transforms (ex. Redpanda 22.3.25):
```json
{
"endpoint": "redpanda.api.console.v1alpha1.TransformService",
"method": "POST",
"isSupported": false
}
```
When we do have WASM transform capability (Redpanda 24.2.1-rc3):
```json
{
"endpoint": "redpanda.api.console.v1alpha1.TransformService",
"method": "POST",
"isSupported": true
}
```
=> backend: add endpoint compatibility check for wasm transforms

frontend/src/components/misc/login.tsx, frontend/src/index.scss, frontend/src/variables.scss
Basic view:
Hover:
OAuth
- We've migrated content to Chakra to be consistent
- Added backup replacements for `--ant-primary-color` and a few other colors until we completely remove all occurencies of `$color-brand-secondary`
- Added spacing between OAuth buttons
Fixes https://github.com/redpanda-data/console-enterprise/issues/268
=> Migrates buttons on login screen to Chakra

frontend/src/components/routes.tsx, frontend/src/config.ts
Attempt to show pipeline service in the sidebar for serverless clusters. ~~It doesn't quite work so I'll ask for some help from console team to fix it.~~ Works now but let me know if this is the right/best way.
related to: https://github.com/redpanda-data/console-enterprise/pull/435
=> frontend: show pipeline service in sidebar for serverless

frontend/src/utils/tsxUtils.tsx
Otherwise may be confusing in case it's being used with Redpanda.
=> frontend: update waiting tooltip text

frontend/src/components/pages/connect/Overview.tsx, frontend/src/components/routes.tsx, frontend/src/config.ts
This PR implements the improvements described in https://github.com/redpanda-data/console-enterprise/issues/455
=> frontend: redpanda connect and kafka connect ux improvements for serverless

frontend/src/components/pages/consumers/Modals.tsx
Fixes a bug when calendar can't be clicked/used inside of an Edit Consumer group modal.
=> Hotfixes calendar opening in consumer groups

frontend/src/components/pages/consumers/Group.Details.tsx
This PR fixes a typo (it's --> its) on the consumer groups page.
The red rectangle annotation was added to the screenshot to illustrate the change.
=> frontend: fix it's/its typo

frontend/src/components/misc/KowlJsonView.tsx
https://github.com/redpanda-data/console/issues/1422
This is a hotfix that works around the issue on how sizes are calculated in Safari when using `automaticLayout: true`
=> Hotfixes KowlEditor resizing in Safari

.github/workflows/buf.yml
Substitute for https://github.com/redpanda-data/console/pull/1425.
Currently the this action fails on PRs from forks due to `aws-actions/configure-aws-credentials` workflow which does not have access to secrets and vars in that context. 
This PR makes the GH Action conditional to only run on PRs from within branches, along with push to master.
This should cover most cases since normally the Console team should be updating the protos.
Exceptions are docs updates by docs team, or external contributions. But we can work around those cases or offer manual fixes.
=> build: run buf action only on triggers from within the repo

backend/pkg/config/kafka_sasl_oauth.go, backend/pkg/kafka/config_helper.go, docs/config/console.yaml
Kafka SASL OAuth supports sending extensions(custom key-value pairs) during OAuth authentication. These extensions are also supported by franz-go(https://pkg.go.dev/github.com/twmb/franz-go/pkg/sasl/oauth).
So this PR adds a support for these custom properties
=> backend: OAuth SASL extensions support

frontend/src/components/pages/rp-connect/Pipelines.Details.tsx
Currently resources display something like: `100m / 400M` which is super confusing, while we should make this better, this is a stop gap solution to at least tell the user what resources these are.
=> rpcn: add description to resources

backend/go.mod, backend/go.sum
Somewhere go mod seems to have broken and the rpadmin module specified doesn't seem valid:
```
github.com/redpanda-data/common-go/rpadmin@v0.1.7-0.20240921114754-0b4b663276c0 invalid version: unknown revision 0b4b663276c0
```
I tagged a new version of the module and added it to go mod.
=> build: update rpadmin module to latest tag

backend/pkg/console/topic_partitions.go
```sh
❯ http http://localhost:9090/api/topics/owlshop-orders-protobuf-plain/partitions
HTTP/1.1 200 OK
App-Build-Timestamp: 1729709471
Content-Type: application/json
Vary: Origin
Date: Wed, 23 Oct 2024 18:52:23 GMT
Content-Length: 255
{
"topicName": "owlshop-orders-protobuf-plain",
"partitions": [
{
"id": 0,
"replicas": [
0
],
"offlineReplicas": null,
"inSyncReplicas": [
0
],
"leader": 0,
"waterMarkLow": 0,
"waterMarkHigh": 7,
"leaderEpoch": 1,
"partitionLogDirs": [
{
"brokerId": 0,
"partitionId": 0,
"size": 12929
}
]
}
]
}
```
=> backend: add leader epoch to partition api response

backend/pkg/console/endpoint_compatibility.go, backend/pkg/redpanda/service.go
When not supported (ex, old version):
```sh
❯ http http://localhost:9090/api/console/endpoints
HTTP/1.1 200 OK
App-Build-Timestamp: 1731510626
Content-Type: application/json
Vary: Origin
Date: Wed, 13 Nov 2024 15:11:02 GMT
Content-Length: 1315
{
"distribution": "redpanda",
"endpointCompatibility": {
"kafkaVersion": "unknown custom version at least v0.11.0",
"endpoints": [
...
{
"endpoint": "redpanda.api.console.v1alpha1.DebugBundleService",
"method": "POST",
"isSupported": false
},
...
]
}
}
```
When is supported:
```sh
❯ http http://localhost:9090/api/console/endpoints
HTTP/1.1 200 OK
App-Build-Timestamp: 1731510626
Content-Type: application/json
Vary: Origin
Date: Wed, 13 Nov 2024 15:10:28 GMT
Content-Length: 1314
{
"distribution": "redpanda",
"endpointCompatibility": {
"kafkaVersion": …
```
=> backend: add debug bundle endpoint compatibility support

frontend/src/components/license/LicenseNotification.tsx
=> Fixes grammar in a license notification banner

frontend/src/components/pages/connect/Overview.tsx, frontend/src/components/pages/rp-connect/Pipelines.Create.tsx, frontend/src/components/pages/rp-connect/Pipelines.Edit.tsx, frontend/src/components/pages/rp-connect/Pipelines.List.tsx, frontend/src/components/pages/rp-connect/secrets/Secrets.Create.tsx, frontend/src/components/pages/rp-connect/secrets/Secrets.List.tsx, frontend/src/components/pages/rp-connect/secrets/Secrets.Update.tsx, frontend/src/components/routes.tsx, frontend/src/config.ts, frontend/src/state/backendApi.ts, frontend/src/state/ui.ts
This PR introduces a new tab for Redpanda Connect
Features:
- Create secrets
- Edit secrets
- Delete secrets
- Update secrets
- Secret autocomplete on pipeline RPCN editor
- Choose which connect tab is showing as default based on query param `defaultTab`
Pending:
https://github.com/user-attachments/assets/88c0ab66-3efe-4091-b821-3436e19109b8
https://github.com/user-attachments/assets/ef115086-2ec2-44fd-b014-43b7c69008a5
https://github.com/user-attachments/assets/f1987f9e-16e5-464c-99ec-872a17a797c1
=> Add redpanda connect secret manager to console

frontend/src/components/pages/overview/Overview.tsx
In case license information fails to fetch (for any reason) we should assume users are already using enterprise and hide this banner. We would like to avoid showing this to upgraded users if there is e.g. network error.
Before:
After:
=> Hides trial banner in case licenses failed to fetch

frontend/src/components/layout/Content.tsx, frontend/src/components/misc/NullFallbackBoundary.tsx, frontend/src/components/pages/acls/Acl.List.tsx, frontend/src/components/pages/overview/Overview.tsx, frontend/src/components/pages/reassign-partitions/ReassignPartitions.tsx
Introduced `NullFallbackBoundary` for silently failing, we shouldn't affect the functionality in case there would be some problem with the code
=> Adds NullFallbackBoundary around license banners

backend/pkg/api/middlewares.go
Update basePathMiddleware to use `RawPath` (if present) over `Path` to ensure that URL path encoded subjects are preserved when routing requests.
Update the middleware to also remove the prefix from `RawPath` for consistency.
Fixes #1525.
=> Preserve path encoded subjects in middleware

frontend/src/components/pages/connect/Overview.tsx, frontend/src/components/pages/rp-connect/secrets/Secrets.Create.tsx, frontend/src/components/pages/rp-connect/secrets/Secrets.List.tsx, frontend/src/components/pages/rp-connect/secrets/Secrets.Update.tsx, frontend/src/state/backendApi.ts
Secret manager will be disabled if `REDPANDA_CONNECT` is not present in secret scopes.
=> Feature/enable RPCN secret by scope

frontend/tsconfig.base.json
Comments in the JSON was causing some IDEs to not accept tsconfig at all.
=> build: remove comments from tsconfig base

frontend/src/components/pages/transforms/Transforms.List.tsx, frontend/src/components/pages/transforms/Transforms.Setup.tsx
Data transforms is no longer in beta. Although we have redirects, it's best to use the GA URL.
=> Fix doc links

frontend/public/index.html
Since a default base tag was added to the index.html, the mechanism for setting a custom BASE_URL is broken. When multiple base tags are present in a html file, only the first tag is used (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base#multiple_base_elements). Therefore, we need to adapt the existing base tag and not append a newly created one.
=> Fix setting of custom BASE_URL in index.html

backend/pkg/proto/service.go, backend/pkg/schema/service.go
I cannot think of a technical reason why we would need the source code info for dynamic Protocol Buffer loading and dynamic compiling and record deserialization.
Turning this off provides sometimes significant improvement in memory usage.
=> INC-640: set IncludeSourceCodeInfo to false

frontend/src/components/pages/rp-connect/Pipelines.Create.tsx
Add secrets autocomplete for editor pipeline
https://github.com/user-attachments/assets/e241de1d-b4fd-4936-87cc-035c4b32fb7c
=> front-end: add secret auto-complete in pipeline yaml editor

frontend/src/components/pages/rp-connect/Pipelines.Create.tsx, frontend/src/components/pages/rp-connect/Pipelines.Details.tsx, frontend/src/components/pages/rp-connect/Pipelines.Edit.tsx
We're using a new term for sizing.
=> rpcn: rename tasks to compute units

frontend/src/components/misc/ConfigList.tsx, frontend/src/components/pages/topics/TopicConfiguration.tsx, frontend/src/state/backendApi.ts
- We needed to remove altering data structures in the backendAPI (moved to ConfigList where it was needed)
- We added an information about default value to the topic config form
=> Show default config for topic configurations

frontend/src/components/pages/connect/dynamic-ui/ConnectorStep.tsx, frontend/src/components/pages/connect/dynamic-ui/PropertyComponent.tsx, frontend/src/components/pages/connect/dynamic-ui/PropertyGroup.tsx, frontend/src/components/pages/connect/dynamic-ui/components.tsx, frontend/src/state/connect/state.ts
Disable change name in edit kafka connect
=> front-end: disable edit name in kafka connectors

frontend/src/components/pages/connect/Connector.Details.tsx
Fix wrong tooltip message in update kafka connector
User with permissions:
(mouse over)
User without permissions:
=> frontend: fix tooltip for edit kafka connector

backend/pkg/api/handle_schema_registry.go, backend/pkg/console/schema_registry.go, backend/pkg/console/servicer.go
There's not much to return when we delete the subject compatibility. Previously it used to fail because there's no enum type for "NoCompat"and then serialization of that failed. The simple fix was to just remove the response as it didn't provide any value anyways.
=> backend (sr): fix subject compat deletion

backend/pkg/api/api.go, backend/pkg/api/connect/interceptor/error_log.go, backend/pkg/api/routes.go, backend/pkg/config/config.go, backend/pkg/config/logging.go, backend/pkg/logging/context.go, backend/pkg/logging/filter_level.go, backend/pkg/logging/logger.go
This allows attaching decorated loggers to the context. Only the error log interceptor will retrieve the logger from context for now, but we may change this in the future.
=> Authn rewrite decorated logger

backend/pkg/api/api.go, backend/pkg/config/startup.go, backend/pkg/console/list_messages_integration_test.go, backend/pkg/console/service.go, backend/pkg/console/servicer.go
Re-adding the kafka startup check.
Success:
```
{"level":"info","ts":"2025-03-14T16:41:18.609Z","msg":"started Redpanda Console","version":"development","built_at":"<not set>"}
{"level":"info","ts":"2025-03-14T16:41:18.609Z","msg":"creating Kafka connect HTTP clients and testing connectivity to all clusters"}
{"level":"info","ts":"2025-03-14T16:41:18.633Z","msg":"tested Kafka connect cluster connectivity","successful_clusters":1,"failed_clusters":0}
{"level":"info","ts":"2025-03-14T16:41:18.633Z","msg":"successfully create Kafka connect service"}
{"level":"info","ts":"2025-03-14T16:41:18.643Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata","seed_brokers":["localhost:19092"]}
{"level":"info","ts":"2025-03-14T16:41:18.673Z","msg":"successfully connected to kafka …
```
=> backend: re-add kafka startup check

frontend/src/components/pages/rp-connect/Pipelines.Edit.tsx, frontend/src/state/backendApi.ts
Bringing in this commit into master.
https://github.com/redpanda-data/console/commit/e9ce83d85bd0b73b45260b3d62b4f3f1925c8f5e
We should generally review and change dataplane `v1alpha2` usage throughout frontend
=> frontend: use v1 data types for requests in frontend

docs/local/docker-compose.yaml
The `docker-compose.yaml` is not working because the name of the redpanda image is wrong.
```
✘ redpanda Error pull access denied for vect...                 1.5s
Error response from daemon: pull access denied for vectorized/redpanda, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
The organization name in the Docker Hub was renamed from `vectorized` to `redpandadata` some time ago.
Updated the image name in the `docker-compose.yaml`
=> Update the name of the redpanda image in the example docker-compose file

frontend/src/components/pages/consumers/Group.Details.tsx, frontend/src/components/pages/consumers/Modals.tsx
- Added a selector for editing single partition.
- Clicking edit button next to the partition will preselect that partition
- Moving to step 2 (preview) will only update offsets of selected partition
=> Console 35 consumer groups rework - single partition offset edit

frontend/src/components/pages/consumers/Group.Details.tsx, frontend/src/components/pages/consumers/Modals.tsx
The group can not be editable when in use.
Disable the edit button when the group is in use by adding the `disabledReason={cannotEditGroupReason(group)}`
The label for the input `Custom offset value` was confusing, since the user is supposed to select a difference to which the offset should be shifted by, and not the offset itself.
Change the label to  just `Shift by`
The shift by number input UIX is not good.
- Impossible to enter negative number by keyboard unless entering the digits first
- Deleting the text shows `NaN`
The state of the field was driven only by value of type number, so the input always had to show a number and not an incomplete text input (like `""` or `"-"`)
Use string value for handling state of the field.
Entering only negative sign `-` without completing the number …
=> Edit Consumer Group modal improvements

frontend/src/components/pages/overview/Overview.tsx, frontend/src/components/pages/topics/Topic.Produce.tsx, frontend/src/state/backendApi.ts, frontend/src/state/restInterfaces.ts, frontend/src/state/ui.ts
=> Better ACL error message in the overview tab

backend/pkg/config/proto.go
We used the `json` struct tags rather than `yaml` struct tags, causing https://github.com/redpanda-data/console/issues/1721
=> backend: fix proto config struct tags

frontend/src/components/pages/topics/Topic.List.tsx, frontend/src/state/backendApi.ts
The problem was in `backendApi.ts:rest` which returns null in some error cases, making FE to believe that the request succeeded. I'll elimiated all usages of this through the app now.
=> Show an error when topic deletion fails

backend/pkg/config/kafka_sasl_oauth.go, backend/pkg/factory/kafka/kafka.go, docs/config/console.yaml
Hi, currently I have use case where I use kubernetes JWT token stored in `/var/run/secrets/kafka/serviceaccount/token` in k8s pod as token to authenticate to kafka. This token is a mounted file and it is gets renewed periodically.  However, the current available options on the console is by using OIDC token endpoint or by providing token value configured via `KAFKA_SASL_OAUTH_TOKEN` env var. 
So, I am thinking to add additional optional configuration to the token file path and read the file to get the content of the content.
Please let me know what you think.
Thanks.
=> Add tokenFilePath support for providing SASL OAuth token via file

frontend/src/globals.scss
I think this regression was caused when because we now do reset CSS with tailwind instead of Chakra, which we've disabled.
=> Adds cursor:pointer for buttons

backend/pkg/console/schema_registry.go
https://redpandadata.atlassian.net/browse/CONSOLE-185
https://redpandadata.atlassian.net/browse/CONSOLE-191
When we have a single subject and version, then gets deleted the main screen shows errors. This PR fixes it.
I think there is still some issues with SR pages, like in the main view, or the referenced by view. But this improves the situation. I need to investigate further.
=> CONSOLE-191: add show deleted flag to schema registry client calls

frontend/src/components/pages/reassign-partitions/components/ActiveReassignments.tsx
Throttling cannot be used for Redpanda because Redpanda auto-throttles as needed. If someone tries to configure throttling the requests will fail. We need to adapt the page and remove the settings if we are running on a Redpanda cluster.
Hide the `Throttle` setting button when the cluster is RedPanda
=> feat: hide throttle button for Redpanda clusters

frontend/src/components/layout/Header.tsx
The `debug bundle` button was visible when embedded in the Cloud
Add a condition `!isEmbedded()` to only render the button in standalone mode
=> Hide debug bundle button in embedded mode

frontend/src/components/layout/Header.tsx
The `Debug bundle` feature should be present only in standalone (non-cloud) mode and not in self-hosted (red panda) mode.
###
Solution
Add the isRedpanda condition to hide the button in self-hosted mode.
=> Only render deebug button for redpanda clusters

backend/go.mod, backend/go.sum, backend/pkg/config/jsonpath/jsonpath.go, backend/pkg/config/jsonpath/jsonpath_test.go
This PR adds a new package for a specific JSON path type, that is supposed to match the type used for `oidc_principal_mapping` in Redpanda core. This is a custom implementation on top of JSON path which allows a transform regex as a suffix. 
This is meant to be used for authentication, but may be valid to be used for other usecases as well. If helpful for other applications such as rpk we can move this type/pkg to the common-go repository.
Jira: CONSOLE-175
=> backend: add jsonpath config pkg

frontend/src/react-query/api/agent.tsx
We were passing the filter with empty string value - previously it did nothing but it was actually meant to be `undefined`.
We cannot filter by name partially because the tags can only be filtered by exact match and the agent name is stored as a tag, not a real pipeline name due to the abstraction living on the frontend. Once we have a dedicated agent service this problem will go away.
This resulted in people seeing this when they created an AI agent.
Recording with fix
https://github.com/user-attachments/assets/623cba21-5834-4eae-aef4-5e9a96ff8d8b
=> frontend: Fix AI agent pipeline filtering

backend/pkg/console/alter_configs.go
If the patch failed on one of the resources, we
were failing to use the proper error message
causing an unexpected panic.
Fixes CONSOLE-181
=> backend: prevent panic on IncrementalAlterConfigs

frontend/src/components/misc/SearchBar.tsx, frontend/src/components/routes.tsx
The route /connected-clusters/redpanda contained infinite render loop
To reproduce:
- run cloudv2 on port 3000
- Go to http://localhost:3000/clusters/d0e8lbgpojcjpdtep250/connect-clusters/redpanda (or other cluster with connector)
Caused by issue in the `SearchBar` component - it was reacting to any observable in the reactive context - some other observable being updated probably caused the issue (unsure which one exactly)
Replaced the mobx's `autorun` in the `SearchBar` component by `reaction` - it does the same but is only triggered when the specified observable changes.
=> Fix infinite render in SearchBar component

frontend/src/components/routes.tsx
Requested by @birdayz to enable testing in serverless
Backporting to 2.8 release, see https://github.com/redpanda-data/console/pull/1790 for 3.0
=> frontend: enable AI agents in serverless UI 2.8

backend/pkg/tls/ca.go, backend/pkg/tls/tls.go
Add option to skip TLS certificate verification when configured. This allows connections to servers with self-signed or otherwise untrusted certificates when InsecureSkipTLSVerify is set in the TLS config.
=> feat(tls): add support for insecure TLS verification

backend/pkg/console/topic_partitions.go
Fixes a bug where all partitions were reporting identical watermark values instead of their individual low/high watermarks. This was causing incorrect "Estimated Messages" calculations in the frontend.
The bug was in `backend/pkg/console/topic_partitions.go` where watermark lookups were using `partition.PartitionID` instead of `partition.ID`. Since `PartitionID` didn't exist in the `TopicPartitionMetadata` struct, Go was returning the zero value (0), causing all partitions to lookup watermarks for partition 0.
- Fixed watermark lookups to use correct field name (`partition.ID`)
- Refactored embedded structs into flat `TopicPartitionDetails` to prevent similar bugs
- Renamed shadowed variable for clarity
- Preserved API compatibility
=> Fix partition watermarks showing identical values across all partitions

backend/pkg/console/delete_topic.go
- Add Topics field to DeleteTopicsRequest for Kafka API v6+ compatibility
- Fixes "No topics set in the response" error for serverless customers
- Ensures compatibility with both v5 (TopicNames) and v6+ (Topics) formats
=> backend: fix topic deletion for Kafka API v6+ compatibility

.github/workflows/buf.yml
- Restructure buf workflow to eliminate redundant validation
- Fix delete event failures when archiving non-existent labels
- Add error handling for archive operations with continue-on-error
- Split validation and registry operations into focused jobs
Auto-deleted branches triggered delete events that tried to archive buf labels that were never created (e.g., frontend-only changes), causing workflow failures.
- `validate` job: runs on both push and pull_request events
- `push-to-registry` job: only handles registry push after validation passes
- `archive-label` job: handles delete events with graceful error handling
- Eliminates redundant linting between PR and push workflows
=> workflows: fix buf workflow delete event handling

frontend/module-federation.js
Required for React 19 upgrade to have smooth transition. This way we should be able to use both React 18 and 19 at the same time across Cloud + Console and different clusters (serverless installpack vs regular)
Similar to https://github.com/redpanda-data/cloudv2/pull/22639
=> frontend: Remove React requiredVersion

backend/.golangci.yaml, backend/go.mod, backend/pkg/logger/example_test.go, backend/pkg/logger/logger.go, backend/pkg/logger/logger_test.go, backend/pkg/logger/options.go, backend/pkg/logger/prometheus.go, backend/pkg/logger/prometheus_test.go
- Add new logger package based on Go's native slog to replace uber/zap
- Provides Prometheus metrics integration for log message counts by level
- Supports configurable handlers with middleware-style extensibility
- Includes JSON/text output formats and custom timestamp formatting
- Preparation for migrating existing zap-based logging to slog
=> backend: add slog-based logger package to replace zap

frontend/src/components/pages/rp-connect/Pipelines.Create.tsx, frontend/src/components/pages/rp-connect/Pipelines.Edit.tsx, frontend/src/components/pages/rp-connect/tasks.tsx, frontend/src/state/backendApi.ts
Sometimes the API adapts automatically the number of compute units, for instance when using an Ollama connector or values in disallowed ranges e.g. 16-31 compute units (since they would use a little part of a dedicated big machine). This adds a warning when the backend does it.
To make it work, I had to do some hacks to have the useToast function available otherwise the local toast would disappear on page change (the "Pipeline created"/"Pipeline updated" toasts did already disappear actually). Pls advise if there's a better way.
=> rpcn: warn when compute units are bumped

backend/.golangci.yaml, backend/pkg/console/consumer_group_delete.go, backend/pkg/console/service.go, backend/pkg/schema/client.go, backend/pkg/serde/service_integration_test.go
Fixes a critical panic that occurs when attempting to deserialize Avro messages while schema registry is disabled. The issue was caused by a nil interface dereference in the serde service when no schema client was available.
- Fix schema client interface to prevent nil interface access when schema registry disabled
- Add comprehensive integration test reproducing the original panic scenario
- Enable nilnesserr linter to catch similar nil interface issues in the future
- Fix unrelated bug in consumer group deletion error handling
Fixes #1842 - Users reported "invalid memory address or nil pointer dereference" panic when viewing messages from topics containing Avro data while schema registry was disabled.
=> backend: fix nil pointer dereference in Avro deserialization

frontend/src/components/pages/schemas/Schema.List.scss, frontend/src/components/pages/schemas/Schema.List.tsx, frontend/src/index.scss
- Add visual highlighting for soft-deleted schema registry subjects in table view
- Implement conditional row styling using DataTable's rowClassName prop  
- Add CSS class with light gray background and muted text for soft-deleted subjects
- Remove unused legacy CSS class from global styles
- `Schema.List.tsx`: Add rowClassName prop to conditionally apply 'soft-deleted-row' class
- `Schema.List.scss`: Add styling for soft-deleted subjects using Chakra UI semantic tokens
- `index.scss`: Remove unused `.subjectSoftDeleted` class
The API already provides `isSoftDeleted` boolean data, this change ensures the UI properly displays the visual separation that was previously missing.
First row is a soft-deleted subject
=> frontend: add visual highlighting for soft-deleted schema registry subjects

CHANGELOG.md, backend/pkg/console/schema_registry.go, frontend/src/components/pages/schemas/Schema.List.tsx
Fixes error handling issues in schema registry compatibility configuration and improves UI visual indicators for better user experience.
- Fix handling of schema registry subject compatibility configuration errors
- Handle 40408 error code (subject compatibility not configured) by returning "DEFAULT"
- Return "UNKNOWN" for other errors instead of failing the entire request
- Change compatibility field from pointer to string for consistency
- Add archive icon with tooltip for soft-deleted subjects
- Add colored badges for schema types (AVRO=blue, PROTOBUF=teal, JSON=orange)
- Show "None" instead of empty space for subjects with no active versions
- Import required icons and UI components
This addresses potential bugs in schema registry client usage that could cause degraded user experience …
=> backend: fix schema registry error handling and UI improvements

backend/go.mod, backend/go.sum, backend/pkg/schema/client_test.go
Now it's released in the latest version, but it's called srfake.
=> be: replace franz-go/sr fork

backend/pkg/api/connect/service/clusterstatus/redpanda.go, backend/pkg/api/connect/service/clusterstatus/service.go
This PR fixes goconst and nolintlint issues by consolidating repeated "unknown" string literals into a single constant. The change addresses linter inconsistencies between local and CI environments where nolint directives behave differently despite using identical golangci-lint versions.
- Added `unknownVersion` constant to replace hardcoded "unknown" strings
- Updated `service.go` to use the constant in two locations (lines 104, 207)  
- Updated `redpanda.go` to use the constant and removed unused nolint directive
- Eliminates goconst violations for repeated string literals
- Resolves nolintlint warnings about unused directives
The CI was reporting linting errors that weren't appearing locally:
- `goconst: string 'unknown' has 3 occurrences, make it a constant`
- `nolintlint: directive …
=> fix: resolve goconst linting issues with unknown string constant

.github/workflows/backend-lint-test.yml, backend/.golangci.yaml, backend/go.mod, backend/go.sum, backend/pkg/connect/get_connectors.go, backend/pkg/schema/service.go, backend/pkg/schema/service_test.go, taskfiles/backend.yaml
Fixes an issue where users experienced compilation errors of their protobuf schemas that resulted in all schemas not being compiled. The problem occurred when some schemas had broken references (e.g., to soft-deleted dependencies in the schema registry).
- **Fault-tolerant compilation**: Replace all-or-nothing approach with best-effort schema compilation
- **Graceful error handling**: Skip problematic schemas instead of aborting entire refresh
- **Enhanced logging**: Warn about failed schemas and provide success/failure metrics
- **Integration test**: Add test case that reproduces and validates the fix
The issue manifested when Console encountered protobuf schemas referencing non-existent or soft-deleted schemas. Previously, this would cause the entire schema compilation process to abort, …
=> fix: implement fault-tolerant protobuf schema compilation

CHANGELOG.md
Updates the changelog with missing entries for v2.8.8, v2.8.9, and v3.2.0 releases, organizing them in proper chronological order.
- Add v3.2.0 changelog entry (2025-08-19)
- Add Redpanda news integration and trial license banner features
- Add sunset header for deprecated API endpoints
- Add Kafka quota APIs support
- Fix schema registry navigation and consumer group offset handling
- Migrate logging from zap to structured slog
- Add v2.8.9 changelog entry (2025-08-05) 
- Implement fault-tolerant protobuf schema compilation
- Fix time format in enterprise features for proper ISO8601 timestamps
- Update franz-go schema registry dependency to v1.5.0
- Add v2.8.8 changelog entry (2025-07-18)
- Fix proto schema cache corruption and key collision
- Reorganize changelog entries to maintain …
=> docs: update changelog with v2.8.8, v2.8.9, and v3.2.0 releases

backend/pkg/console/endpoint_compatibility.go, backend/pkg/console/redpanda_feature.go, backend/pkg/serde/protobuf.go
This one is a compromise: as the ACL service is
always present, we are adding the service to this
list, but assuming is the Schema Registry feature.
So, now, the frontend could query /endpoints to
determine whether to render the schema registry
components on the ACL page.
```
GET /api/console/endpoints
{
"endpoint": "redpanda.api.dataplane.v1.ACLService",
"method": "POST",
"isSupported": true
},
OR
{
"endpoint": "redpanda.api.dataplane.v1.ACLService",
"method": "POST",
"isSupported": false
},
```
=> endpoints: add ACL service for Schema Registry

frontend/src/components/constants.ts, frontend/src/components/pages/remote-mcp/details/remote-mcp-details-page.tsx, frontend/src/components/routes.tsx
Adds 2 feature flags:
- `enableRemoteMcpInConsole` decides whether to show the Remote MCP page.
- `enableRemoteMcpInspectorInConsole` decides whether to show the "Inspector" tab in the details view.
=> frontend: add feature flag for remote MCP

frontend/src/components/pages/remote-mcp/details/inspector/remote-mcp-inspector-parameters.tsx, frontend/src/components/pages/remote-mcp/list/remote-mcp-list-page.tsx, frontend/src/react-query/api/remote-mcp.tsx, frontend/src/state/supportedFeatures.ts
Fix for [AI-112](https://redpandadata.atlassian.net/browse/AI-112).
We first needed the `/initialize` step before we are able to call the MCP tools with the correct `Mcp-Session-Id` header, which we get from the response. Thanks @birdayz for making me realize it 😓 
In the future we can move to a proper MCP client setup instead of just doing the `fetch()` API if we feel like it's better.
@birdayz is setting up the `access-control-expose-headers` so that the response headers are exposed to the frontend.
The code snippets still need updating, we can do it in another PR.
[AI-112]: https://redpandadata.atlassian.net/browse/AI-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> frontend: fix remote MCP tool calling

frontend/src/components/pages/admin/Admin.DebugBundle.tsx
This PR introduces two changes to our custom form in the debug bundle:
1. Added units to fields that were previously missing them (size and duration).
2. The form now comes pre-filled with default values, making it easier for customers who only need to change a single field.
=> UI: Custom debug bundle form improvements

backend/pkg/serde/protobuf.go
We will migrate this to the new buf proto package
soon. For now we ignore this deprecation warning.
=> chore: fix linter warning

backend/pkg/factory/kafka/client_hooks.go, backend/pkg/factory/kafka/kafka.go
Adds Prometheus metrics to monitor Kafka broker connections and active client instances for improved observability.
- **New metrics**: `kafka_open_connections` gauge tracks broker connections
- **New metrics**: `kafka_active_clients` gauge tracks client instances  
- **Connection tracking**: Automatic increment/decrement via broker connect/disconnect hooks
- **Client tracking**: Exported functions for client lifecycle management
- **Error handling**: Enhanced client creation with proper error propagation
This provides better visibility into Kafka connection health and resource usage patterns.
=> feat: add Kafka connection and client metrics

backend/pkg/api/api.go, backend/pkg/api/routes.go, backend/pkg/console/cluster_info_integration_test.go, backend/pkg/console/list_messages_integration_test.go, backend/pkg/console/log_dir_topic_test.go, backend/pkg/console/topic_config_integration_test.go, backend/pkg/factory/kafka/client_hooks.go, backend/pkg/factory/kafka/kafka.go
- Enables injection of custom Prometheus registry for Kafka client metrics
- Replaces global registry usage with per-registry metric management
- Maintains all existing metrics functionality including active client tracking
- Modified `client_hooks.go` to support per-registry metrics instead of global promauto
- Updated `CachedClientProvider` to accept and use injected Prometheus registry
- Fixed `/admin/metrics` endpoint to use injected registry
- Updated test files to pass registry parameter
This allows enterprise repos to inject their own Prometheus registry while preserving all Kafka metrics collection.
=> feat: support custom Prometheus registry for Kafka metrics

frontend/src/components/routes.tsx
Disables knowledge bases in Serverless regardless of the LaunchDarkly feature flag.
=> frontend: disable knowledge bases in serverless

frontend/src/components/pages/acls/new-acl/CreateACL.tsx, frontend/tests/console/acl.spec.ts, frontend/tests/console/pages/ACLPage.ts
**ACL Resource Type Handling:**
- Changed the logic in `CreateACL.tsx` to always set the default resource type to `ResourceTypeTopic` when cluster rules exist, removing the previous check for subject rules.
- Updated the list of resource types to only include `ResourceTypeSubject` and `ResourceTypeSchemaRegistry` if `schemaRegistryEnabled` is true, preventing them from being included by default.
https://github.com/user-attachments/assets/507f5b25-a0b1-464d-adb4-db1241a23a72
=> Fix: ACL page, allow all with schema registry acl

backend/pkg/factory/kafka/client_hooks.go, backend/pkg/factory/kafka/kafka.go
- Temporarily disable Kafka client cache to troubleshoot connection issues
- Add enhanced connection monitoring and tracing capabilities
- Remove deprecated call trace functionality that provided no value
- Clean up commented cache configuration code
- Disabled client caching in `CachedClientProvider`
- Added comprehensive Kafka client metrics and monitoring
- Enhanced connection tracing for debugging purposes
- Removed unused call trace debug functionality
- Code cleanup and formatting improvements
=> debug: remove Kafka client cache expiry

frontend/CLAUDE.md, frontend/src/components/pages/mcp-servers/connect-client-guide/__snapshots__/utils.test.ts.snap, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/auggie.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/claude-code.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/claude-desktop.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/cline.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/codex.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/cursor.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/gemini.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/manus.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/vscode.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/warp.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/clients/windsurf.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/remote-mcp-connect-client-guide.tsx, frontend/src/components/pages/mcp-servers/connect-client-guide/utils.test.ts, frontend/src/components/pages/mcp-servers/connect-client-guide/utils.ts
This PR:
- moves to enums so that all cases are covered.
- adds unit tests
- prevents adding `"-X"` flag when `rpk cloud mcp proxy` command is used in production.
=> frontend: rpk cloud mcp proxy flag fixes
